// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentLoginResponse.proto

package com.vcbl.tabbanking.protobuff;

public final class AgentLoginResponse {
  private AgentLoginResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code VCBL.AgentLogin.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAILURE = 1;</code>
     */
    FAILURE(1),
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FAILURE = 1;</code>
     */
    public static final int FAILURE_VALUE = 1;
    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 1: return FAILURE;
        case 0: return SUCCESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return  AgentLoginResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:VCBL.AgentLogin.Status)
  }

  public interface AgentLoginResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VCBL.AgentLogin.AgentLoginRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string protoVersion = 1;</code>
     */
    String getProtoVersion();
    /**
     * <code>string protoVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getProtoVersionBytes();

    /**
     * <code>string appsVersion = 2;</code>
     */
    String getAppsVersion();
    /**
     * <code>string appsVersion = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppsVersionBytes();

    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 3;</code>
     */
    String getTimeStamp();
    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>string POSIdId = 4;</code>
     */
    String getPOSIdId();
    /**
     * <code>string POSIdId = 4;</code>
     */
    com.google.protobuf.ByteString
        getPOSIdIdBytes();

    /**
     * <code>string bcid = 6;</code>
     */
    String getBcid();
    /**
     * <code>string bcid = 6;</code>
     */
    com.google.protobuf.ByteString
        getBcidBytes();

    /**
     * <code>string roleid = 7;</code>
     */
    String getRoleid();
    /**
     * <code>string roleid = 7;</code>
     */
    com.google.protobuf.ByteString
        getRoleidBytes();

    /**
     * <code>string pin = 8;</code>
     */
    String getPin();
    /**
     * <code>string pin = 8;</code>
     */
    com.google.protobuf.ByteString
        getPinBytes();

    /**
     * <code>string fps_data = 9;</code>
     */
    String getFpsData();
    /**
     * <code>string fps_data = 9;</code>
     */
    com.google.protobuf.ByteString
        getFpsDataBytes();

    /**
     * <code>string branchid = 10;</code>
     */
    String getBranchid();
    /**
     * <code>string branchid = 10;</code>
     */
    com.google.protobuf.ByteString
        getBranchidBytes();

    /**
     * <code>.VCBL.AgentLogin.Status status = 11;</code>
     */
    int getStatusValue();
    /**
     * <code>.VCBL.AgentLogin.Status status = 11;</code>
     */
     AgentLoginResponse.Status getStatus();

    /**
     * <code>string statusDescription = 12;</code>
     */
    String getStatusDescription();
    /**
     * <code>string statusDescription = 12;</code>
     */
    com.google.protobuf.ByteString
        getStatusDescriptionBytes();
  }
  /**
   * Protobuf type {@code VCBL.AgentLogin.AgentLoginRes}
   */
  public  static final class AgentLoginRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VCBL.AgentLogin.AgentLoginRes)
      AgentLoginResOrBuilder {
    // Use AgentLoginRes.newBuilder() to construct.
    private AgentLoginRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AgentLoginRes() {
      protoVersion_ = "";
      appsVersion_ = "";
      timeStamp_ = "";
      pOSIdId_ = "";
      bcid_ = "";
      roleid_ = "";
      pin_ = "";
      fpsData_ = "";
      branchid_ = "";
      status_ = 0;
      statusDescription_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AgentLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              protoVersion_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              appsVersion_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              timeStamp_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              pOSIdId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              bcid_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              roleid_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              pin_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              fpsData_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              branchid_ = s;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              statusDescription_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return  AgentLoginResponse.internal_static_VCBL_AgentLogin_AgentLoginRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return  AgentLoginResponse.internal_static_VCBL_AgentLogin_AgentLoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
               AgentLoginResponse.AgentLoginRes.class,  AgentLoginResponse.AgentLoginRes.Builder.class);
    }

    public static final int PROTOVERSION_FIELD_NUMBER = 1;
    private volatile Object protoVersion_;
    /**
     * <code>string protoVersion = 1;</code>
     */
    public String getProtoVersion() {
      Object ref = protoVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protoVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string protoVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProtoVersionBytes() {
      Object ref = protoVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protoVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPSVERSION_FIELD_NUMBER = 2;
    private volatile Object appsVersion_;
    /**
     * <code>string appsVersion = 2;</code>
     */
    public String getAppsVersion() {
      Object ref = appsVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appsVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string appsVersion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppsVersionBytes() {
      Object ref = appsVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appsVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile Object timeStamp_;
    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 3;</code>
     */
    public String getTimeStamp() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSIDID_FIELD_NUMBER = 4;
    private volatile Object pOSIdId_;
    /**
     * <code>string POSIdId = 4;</code>
     */
    public String getPOSIdId() {
      Object ref = pOSIdId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pOSIdId_ = s;
        return s;
      }
    }
    /**
     * <code>string POSIdId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPOSIdIdBytes() {
      Object ref = pOSIdId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pOSIdId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BCID_FIELD_NUMBER = 6;
    private volatile Object bcid_;
    /**
     * <code>string bcid = 6;</code>
     */
    public String getBcid() {
      Object ref = bcid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bcid_ = s;
        return s;
      }
    }
    /**
     * <code>string bcid = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBcidBytes() {
      Object ref = bcid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bcid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLEID_FIELD_NUMBER = 7;
    private volatile Object roleid_;
    /**
     * <code>string roleid = 7;</code>
     */
    public String getRoleid() {
      Object ref = roleid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roleid_ = s;
        return s;
      }
    }
    /**
     * <code>string roleid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRoleidBytes() {
      Object ref = roleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIN_FIELD_NUMBER = 8;
    private volatile Object pin_;
    /**
     * <code>string pin = 8;</code>
     */
    public String getPin() {
      Object ref = pin_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pin_ = s;
        return s;
      }
    }
    /**
     * <code>string pin = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPinBytes() {
      Object ref = pin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FPS_DATA_FIELD_NUMBER = 9;
    private volatile Object fpsData_;
    /**
     * <code>string fps_data = 9;</code>
     */
    public String getFpsData() {
      Object ref = fpsData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fpsData_ = s;
        return s;
      }
    }
    /**
     * <code>string fps_data = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFpsDataBytes() {
      Object ref = fpsData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fpsData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRANCHID_FIELD_NUMBER = 10;
    private volatile Object branchid_;
    /**
     * <code>string branchid = 10;</code>
     */
    public String getBranchid() {
      Object ref = branchid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        branchid_ = s;
        return s;
      }
    }
    /**
     * <code>string branchid = 10;</code>
     */
    public com.google.protobuf.ByteString
        getBranchidBytes() {
      Object ref = branchid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        branchid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 11;
    private int status_;
    /**
     * <code>.VCBL.AgentLogin.Status status = 11;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.VCBL.AgentLogin.Status status = 11;</code>
     */
    public  AgentLoginResponse.Status getStatus() {
       AgentLoginResponse.Status result =  AgentLoginResponse.Status.valueOf(status_);
      return result == null ?  AgentLoginResponse.Status.UNRECOGNIZED : result;
    }

    public static final int STATUSDESCRIPTION_FIELD_NUMBER = 12;
    private volatile Object statusDescription_;
    /**
     * <code>string statusDescription = 12;</code>
     */
    public String getStatusDescription() {
      Object ref = statusDescription_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        statusDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string statusDescription = 12;</code>
     */
    public com.google.protobuf.ByteString
        getStatusDescriptionBytes() {
      Object ref = statusDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        statusDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProtoVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, protoVersion_);
      }
      if (!getAppsVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appsVersion_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timeStamp_);
      }
      if (!getPOSIdIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pOSIdId_);
      }
      if (!getBcidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bcid_);
      }
      if (!getRoleidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, roleid_);
      }
      if (!getPinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pin_);
      }
      if (!getFpsDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, fpsData_);
      }
      if (!getBranchidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, branchid_);
      }
      if (status_ !=  AgentLoginResponse.Status.FAILURE.getNumber()) {
        output.writeEnum(11, status_);
      }
      if (!getStatusDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, statusDescription_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProtoVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, protoVersion_);
      }
      if (!getAppsVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appsVersion_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timeStamp_);
      }
      if (!getPOSIdIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pOSIdId_);
      }
      if (!getBcidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bcid_);
      }
      if (!getRoleidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, roleid_);
      }
      if (!getPinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pin_);
      }
      if (!getFpsDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, fpsData_);
      }
      if (!getBranchidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, branchid_);
      }
      if (status_ !=  AgentLoginResponse.Status.FAILURE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, status_);
      }
      if (!getStatusDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, statusDescription_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof  AgentLoginResponse.AgentLoginRes)) {
        return super.equals(obj);
      }
       AgentLoginResponse.AgentLoginRes other = ( AgentLoginResponse.AgentLoginRes) obj;

      boolean result = true;
      result = result && getProtoVersion()
          .equals(other.getProtoVersion());
      result = result && getAppsVersion()
          .equals(other.getAppsVersion());
      result = result && getTimeStamp()
          .equals(other.getTimeStamp());
      result = result && getPOSIdId()
          .equals(other.getPOSIdId());
      result = result && getBcid()
          .equals(other.getBcid());
      result = result && getRoleid()
          .equals(other.getRoleid());
      result = result && getPin()
          .equals(other.getPin());
      result = result && getFpsData()
          .equals(other.getFpsData());
      result = result && getBranchid()
          .equals(other.getBranchid());
      result = result && status_ == other.status_;
      result = result && getStatusDescription()
          .equals(other.getStatusDescription());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getProtoVersion().hashCode();
      hash = (37 * hash) + APPSVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppsVersion().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (37 * hash) + POSIDID_FIELD_NUMBER;
      hash = (53 * hash) + getPOSIdId().hashCode();
      hash = (37 * hash) + BCID_FIELD_NUMBER;
      hash = (53 * hash) + getBcid().hashCode();
      hash = (37 * hash) + ROLEID_FIELD_NUMBER;
      hash = (53 * hash) + getRoleid().hashCode();
      hash = (37 * hash) + PIN_FIELD_NUMBER;
      hash = (53 * hash) + getPin().hashCode();
      hash = (37 * hash) + FPS_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getFpsData().hashCode();
      hash = (37 * hash) + BRANCHID_FIELD_NUMBER;
      hash = (53 * hash) + getBranchid().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + STATUSDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getStatusDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static  AgentLoginResponse.AgentLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static  AgentLoginResponse.AgentLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static  AgentLoginResponse.AgentLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static  AgentLoginResponse.AgentLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder( AgentLoginResponse.AgentLoginRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VCBL.AgentLogin.AgentLoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VCBL.AgentLogin.AgentLoginRes)
         AgentLoginResponse.AgentLoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  AgentLoginResponse.internal_static_VCBL_AgentLogin_AgentLoginRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  AgentLoginResponse.internal_static_VCBL_AgentLogin_AgentLoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                 AgentLoginResponse.AgentLoginRes.class,  AgentLoginResponse.AgentLoginRes.Builder.class);
      }

      // Construct using  AgentLoginResponse.AgentLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        protoVersion_ = "";

        appsVersion_ = "";

        timeStamp_ = "";

        pOSIdId_ = "";

        bcid_ = "";

        roleid_ = "";

        pin_ = "";

        fpsData_ = "";

        branchid_ = "";

        status_ = 0;

        statusDescription_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  AgentLoginResponse.internal_static_VCBL_AgentLogin_AgentLoginRes_descriptor;
      }

      public  AgentLoginResponse.AgentLoginRes getDefaultInstanceForType() {
        return  AgentLoginResponse.AgentLoginRes.getDefaultInstance();
      }

      public  AgentLoginResponse.AgentLoginRes build() {
         AgentLoginResponse.AgentLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public  AgentLoginResponse.AgentLoginRes buildPartial() {
         AgentLoginResponse.AgentLoginRes result = new  AgentLoginResponse.AgentLoginRes(this);
        result.protoVersion_ = protoVersion_;
        result.appsVersion_ = appsVersion_;
        result.timeStamp_ = timeStamp_;
        result.pOSIdId_ = pOSIdId_;
        result.bcid_ = bcid_;
        result.roleid_ = roleid_;
        result.pin_ = pin_;
        result.fpsData_ = fpsData_;
        result.branchid_ = branchid_;
        result.status_ = status_;
        result.statusDescription_ = statusDescription_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof  AgentLoginResponse.AgentLoginRes) {
          return mergeFrom(( AgentLoginResponse.AgentLoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom( AgentLoginResponse.AgentLoginRes other) {
        if (other ==  AgentLoginResponse.AgentLoginRes.getDefaultInstance()) return this;
        if (!other.getProtoVersion().isEmpty()) {
          protoVersion_ = other.protoVersion_;
          onChanged();
        }
        if (!other.getAppsVersion().isEmpty()) {
          appsVersion_ = other.appsVersion_;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (!other.getPOSIdId().isEmpty()) {
          pOSIdId_ = other.pOSIdId_;
          onChanged();
        }
        if (!other.getBcid().isEmpty()) {
          bcid_ = other.bcid_;
          onChanged();
        }
        if (!other.getRoleid().isEmpty()) {
          roleid_ = other.roleid_;
          onChanged();
        }
        if (!other.getPin().isEmpty()) {
          pin_ = other.pin_;
          onChanged();
        }
        if (!other.getFpsData().isEmpty()) {
          fpsData_ = other.fpsData_;
          onChanged();
        }
        if (!other.getBranchid().isEmpty()) {
          branchid_ = other.branchid_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getStatusDescription().isEmpty()) {
          statusDescription_ = other.statusDescription_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
         AgentLoginResponse.AgentLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = ( AgentLoginResponse.AgentLoginRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object protoVersion_ = "";
      /**
       * <code>string protoVersion = 1;</code>
       */
      public String getProtoVersion() {
        Object ref = protoVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          protoVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string protoVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProtoVersionBytes() {
        Object ref = protoVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          protoVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string protoVersion = 1;</code>
       */
      public Builder setProtoVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        protoVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string protoVersion = 1;</code>
       */
      public Builder clearProtoVersion() {
        
        protoVersion_ = getDefaultInstance().getProtoVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string protoVersion = 1;</code>
       */
      public Builder setProtoVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        protoVersion_ = value;
        onChanged();
        return this;
      }

      private Object appsVersion_ = "";
      /**
       * <code>string appsVersion = 2;</code>
       */
      public String getAppsVersion() {
        Object ref = appsVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appsVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appsVersion = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppsVersionBytes() {
        Object ref = appsVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appsVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appsVersion = 2;</code>
       */
      public Builder setAppsVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appsVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appsVersion = 2;</code>
       */
      public Builder clearAppsVersion() {
        
        appsVersion_ = getDefaultInstance().getAppsVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string appsVersion = 2;</code>
       */
      public Builder setAppsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appsVersion_ = value;
        onChanged();
        return this;
      }

      private Object timeStamp_ = "";
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 3;</code>
       */
      public String getTimeStamp() {
        Object ref = timeStamp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 3;</code>
       */
      public Builder setTimeStamp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 3;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 3;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private Object pOSIdId_ = "";
      /**
       * <code>string POSIdId = 4;</code>
       */
      public String getPOSIdId() {
        Object ref = pOSIdId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pOSIdId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string POSIdId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPOSIdIdBytes() {
        Object ref = pOSIdId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pOSIdId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string POSIdId = 4;</code>
       */
      public Builder setPOSIdId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pOSIdId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string POSIdId = 4;</code>
       */
      public Builder clearPOSIdId() {
        
        pOSIdId_ = getDefaultInstance().getPOSIdId();
        onChanged();
        return this;
      }
      /**
       * <code>string POSIdId = 4;</code>
       */
      public Builder setPOSIdIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pOSIdId_ = value;
        onChanged();
        return this;
      }

      private Object bcid_ = "";
      /**
       * <code>string bcid = 6;</code>
       */
      public String getBcid() {
        Object ref = bcid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bcid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string bcid = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBcidBytes() {
        Object ref = bcid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bcid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bcid = 6;</code>
       */
      public Builder setBcid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bcid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bcid = 6;</code>
       */
      public Builder clearBcid() {
        
        bcid_ = getDefaultInstance().getBcid();
        onChanged();
        return this;
      }
      /**
       * <code>string bcid = 6;</code>
       */
      public Builder setBcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bcid_ = value;
        onChanged();
        return this;
      }

      private Object roleid_ = "";
      /**
       * <code>string roleid = 7;</code>
       */
      public String getRoleid() {
        Object ref = roleid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roleid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string roleid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRoleidBytes() {
        Object ref = roleid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roleid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roleid = 7;</code>
       */
      public Builder setRoleid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roleid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roleid = 7;</code>
       */
      public Builder clearRoleid() {
        
        roleid_ = getDefaultInstance().getRoleid();
        onChanged();
        return this;
      }
      /**
       * <code>string roleid = 7;</code>
       */
      public Builder setRoleidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roleid_ = value;
        onChanged();
        return this;
      }

      private Object pin_ = "";
      /**
       * <code>string pin = 8;</code>
       */
      public String getPin() {
        Object ref = pin_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pin_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pin = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPinBytes() {
        Object ref = pin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pin = 8;</code>
       */
      public Builder setPin(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pin = 8;</code>
       */
      public Builder clearPin() {
        
        pin_ = getDefaultInstance().getPin();
        onChanged();
        return this;
      }
      /**
       * <code>string pin = 8;</code>
       */
      public Builder setPinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pin_ = value;
        onChanged();
        return this;
      }

      private Object fpsData_ = "";
      /**
       * <code>string fps_data = 9;</code>
       */
      public String getFpsData() {
        Object ref = fpsData_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fpsData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fps_data = 9;</code>
       */
      public com.google.protobuf.ByteString
          getFpsDataBytes() {
        Object ref = fpsData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fpsData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fps_data = 9;</code>
       */
      public Builder setFpsData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fpsData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fps_data = 9;</code>
       */
      public Builder clearFpsData() {
        
        fpsData_ = getDefaultInstance().getFpsData();
        onChanged();
        return this;
      }
      /**
       * <code>string fps_data = 9;</code>
       */
      public Builder setFpsDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fpsData_ = value;
        onChanged();
        return this;
      }

      private Object branchid_ = "";
      /**
       * <code>string branchid = 10;</code>
       */
      public String getBranchid() {
        Object ref = branchid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          branchid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string branchid = 10;</code>
       */
      public com.google.protobuf.ByteString
          getBranchidBytes() {
        Object ref = branchid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          branchid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string branchid = 10;</code>
       */
      public Builder setBranchid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        branchid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string branchid = 10;</code>
       */
      public Builder clearBranchid() {
        
        branchid_ = getDefaultInstance().getBranchid();
        onChanged();
        return this;
      }
      /**
       * <code>string branchid = 10;</code>
       */
      public Builder setBranchidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        branchid_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.VCBL.AgentLogin.Status status = 11;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.VCBL.AgentLogin.Status status = 11;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.VCBL.AgentLogin.Status status = 11;</code>
       */
      public  AgentLoginResponse.Status getStatus() {
         AgentLoginResponse.Status result =  AgentLoginResponse.Status.valueOf(status_);
        return result == null ?  AgentLoginResponse.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.VCBL.AgentLogin.Status status = 11;</code>
       */
      public Builder setStatus( AgentLoginResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.VCBL.AgentLogin.Status status = 11;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object statusDescription_ = "";
      /**
       * <code>string statusDescription = 12;</code>
       */
      public String getStatusDescription() {
        Object ref = statusDescription_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          statusDescription_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string statusDescription = 12;</code>
       */
      public com.google.protobuf.ByteString
          getStatusDescriptionBytes() {
        Object ref = statusDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          statusDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statusDescription = 12;</code>
       */
      public Builder setStatusDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string statusDescription = 12;</code>
       */
      public Builder clearStatusDescription() {
        
        statusDescription_ = getDefaultInstance().getStatusDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string statusDescription = 12;</code>
       */
      public Builder setStatusDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusDescription_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VCBL.AgentLogin.AgentLoginRes)
    }

    // @@protoc_insertion_point(class_scope:VCBL.AgentLogin.AgentLoginRes)
    private static final  AgentLoginResponse.AgentLoginRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new  AgentLoginResponse.AgentLoginRes();
    }

    public static  AgentLoginResponse.AgentLoginRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AgentLoginRes>
        PARSER = new com.google.protobuf.AbstractParser<AgentLoginRes>() {
      public AgentLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AgentLoginRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AgentLoginRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AgentLoginRes> getParserForType() {
      return PARSER;
    }

    public  AgentLoginResponse.AgentLoginRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VCBL_AgentLogin_AgentLoginRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VCBL_AgentLogin_AgentLoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030AgentLoginResponse.proto\022\017VCBL.AgentLo" +
      "gin\"\361\001\n\rAgentLoginRes\022\024\n\014protoVersion\030\001 " +
      "\001(\t\022\023\n\013appsVersion\030\002 \001(\t\022\021\n\ttimeStamp\030\003 " +
      "\001(\t\022\017\n\007POSIdId\030\004 \001(\t\022\014\n\004bcid\030\006 \001(\t\022\016\n\006ro" +
      "leid\030\007 \001(\t\022\013\n\003pin\030\010 \001(\t\022\020\n\010fps_data\030\t \001(" +
      "\t\022\020\n\010branchid\030\n \001(\t\022\'\n\006status\030\013 \001(\0162\027.VC" +
      "BL.AgentLogin.Status\022\031\n\021statusDescriptio" +
      "n\030\014 \001(\t*\"\n\006Status\022\013\n\007FAILURE\020\000\022\013\n\007SUCCES" +
      "S\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VCBL_AgentLogin_AgentLoginRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VCBL_AgentLogin_AgentLoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VCBL_AgentLogin_AgentLoginRes_descriptor,
        new String[] { "ProtoVersion", "AppsVersion", "TimeStamp", "POSIdId", "Bcid", "Roleid", "Pin", "FpsData", "Branchid", "Status", "StatusDescription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
