// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BCTxnSummaryResponse.proto

package com.vcbl.tabbanking.protobuff;

public final class BCTxnSummaryResponse {
    private BCTxnSummaryResponse() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface BCTxnSummaryOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.vcbl.tabbanking.protobuff.BCTxnSummary)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string agentName = 1;</code>
         */
        String getAgentName();

        /**
         * <code>string agentName = 1;</code>
         */
        com.google.protobuf.ByteString
        getAgentNameBytes();

        /**
         * <code>string branchName = 2;</code>
         */
        String getBranchName();

        /**
         * <code>string branchName = 2;</code>
         */
        com.google.protobuf.ByteString
        getBranchNameBytes();

        /**
         * <code>string noofDeposits = 3;</code>
         */
        String getNoofDeposits();

        /**
         * <code>string noofDeposits = 3;</code>
         */
        com.google.protobuf.ByteString
        getNoofDepositsBytes();

        /**
         * <code>string totalDepositAmount = 4;</code>
         */
        String getTotalDepositAmount();

        /**
         * <code>string totalDepositAmount = 4;</code>
         */
        com.google.protobuf.ByteString
        getTotalDepositAmountBytes();

        /**
         * <code>string noofLoanDeposits = 5;</code>
         */
        String getNoofLoanDeposits();

        /**
         * <code>string noofLoanDeposits = 5;</code>
         */
        com.google.protobuf.ByteString
        getNoofLoanDepositsBytes();

        /**
         * <code>string totalLoanDepositAmount = 6;</code>
         */
        String getTotalLoanDepositAmount();

        /**
         * <code>string totalLoanDepositAmount = 6;</code>
         */
        com.google.protobuf.ByteString
        getTotalLoanDepositAmountBytes();

        /**
         * <code>string noofSavingDeposits = 7;</code>
         */
        String getNoofSavingDeposits();

        /**
         * <code>string noofSavingDeposits = 7;</code>
         */
        com.google.protobuf.ByteString
        getNoofSavingDepositsBytes();

        /**
         * <code>string totalSavingDepositAmount = 8;</code>
         */
        String getTotalSavingDepositAmount();

        /**
         * <code>string totalSavingDepositAmount = 8;</code>
         */
        com.google.protobuf.ByteString
        getTotalSavingDepositAmountBytes();

        /**
         * <code>int32 serviceid = 9;</code>
         */
        int getServiceid();

        /**
         * <code>int32 subServiceid = 10;</code>
         */
        int getSubServiceid();
    }

    /**
     * Protobuf type {@code com.vcbl.tabbanking.protobuff.BCTxnSummary}
     */
    public static final class BCTxnSummary extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.vcbl.tabbanking.protobuff.BCTxnSummary)
            BCTxnSummaryOrBuilder {
        // Use BCTxnSummary.newBuilder() to construct.
        private BCTxnSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BCTxnSummary() {
            agentName_ = "";
            branchName_ = "";
            noofDeposits_ = "";
            totalDepositAmount_ = "";
            noofLoanDeposits_ = "";
            totalLoanDepositAmount_ = "";
            noofSavingDeposits_ = "";
            totalSavingDepositAmount_ = "";
            serviceid_ = 0;
            subServiceid_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private BCTxnSummary(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            agentName_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            branchName_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            noofDeposits_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            totalDepositAmount_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            noofLoanDeposits_ = s;
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();

                            totalLoanDepositAmount_ = s;
                            break;
                        }
                        case 58: {
                            String s = input.readStringRequireUtf8();

                            noofSavingDeposits_ = s;
                            break;
                        }
                        case 66: {
                            String s = input.readStringRequireUtf8();

                            totalSavingDepositAmount_ = s;
                            break;
                        }
                        case 72: {

                            serviceid_ = input.readInt32();
                            break;
                        }
                        case 80: {

                            subServiceid_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.class, com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.Builder.class);
        }

        public static final int AGENTNAME_FIELD_NUMBER = 1;
        private volatile Object agentName_;

        /**
         * <code>string agentName = 1;</code>
         */
        public String getAgentName() {
            Object ref = agentName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                agentName_ = s;
                return s;
            }
        }

        /**
         * <code>string agentName = 1;</code>
         */
        public com.google.protobuf.ByteString
        getAgentNameBytes() {
            Object ref = agentName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                agentName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRANCHNAME_FIELD_NUMBER = 2;
        private volatile Object branchName_;

        /**
         * <code>string branchName = 2;</code>
         */
        public String getBranchName() {
            Object ref = branchName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                branchName_ = s;
                return s;
            }
        }

        /**
         * <code>string branchName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getBranchNameBytes() {
            Object ref = branchName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                branchName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NOOFDEPOSITS_FIELD_NUMBER = 3;
        private volatile Object noofDeposits_;

        /**
         * <code>string noofDeposits = 3;</code>
         */
        public String getNoofDeposits() {
            Object ref = noofDeposits_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                noofDeposits_ = s;
                return s;
            }
        }

        /**
         * <code>string noofDeposits = 3;</code>
         */
        public com.google.protobuf.ByteString
        getNoofDepositsBytes() {
            Object ref = noofDeposits_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                noofDeposits_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TOTALDEPOSITAMOUNT_FIELD_NUMBER = 4;
        private volatile Object totalDepositAmount_;

        /**
         * <code>string totalDepositAmount = 4;</code>
         */
        public String getTotalDepositAmount() {
            Object ref = totalDepositAmount_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                totalDepositAmount_ = s;
                return s;
            }
        }

        /**
         * <code>string totalDepositAmount = 4;</code>
         */
        public com.google.protobuf.ByteString
        getTotalDepositAmountBytes() {
            Object ref = totalDepositAmount_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                totalDepositAmount_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NOOFLOANDEPOSITS_FIELD_NUMBER = 5;
        private volatile Object noofLoanDeposits_;

        /**
         * <code>string noofLoanDeposits = 5;</code>
         */
        public String getNoofLoanDeposits() {
            Object ref = noofLoanDeposits_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                noofLoanDeposits_ = s;
                return s;
            }
        }

        /**
         * <code>string noofLoanDeposits = 5;</code>
         */
        public com.google.protobuf.ByteString
        getNoofLoanDepositsBytes() {
            Object ref = noofLoanDeposits_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                noofLoanDeposits_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TOTALLOANDEPOSITAMOUNT_FIELD_NUMBER = 6;
        private volatile Object totalLoanDepositAmount_;

        /**
         * <code>string totalLoanDepositAmount = 6;</code>
         */
        public String getTotalLoanDepositAmount() {
            Object ref = totalLoanDepositAmount_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                totalLoanDepositAmount_ = s;
                return s;
            }
        }

        /**
         * <code>string totalLoanDepositAmount = 6;</code>
         */
        public com.google.protobuf.ByteString
        getTotalLoanDepositAmountBytes() {
            Object ref = totalLoanDepositAmount_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                totalLoanDepositAmount_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NOOFSAVINGDEPOSITS_FIELD_NUMBER = 7;
        private volatile Object noofSavingDeposits_;

        /**
         * <code>string noofSavingDeposits = 7;</code>
         */
        public String getNoofSavingDeposits() {
            Object ref = noofSavingDeposits_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                noofSavingDeposits_ = s;
                return s;
            }
        }

        /**
         * <code>string noofSavingDeposits = 7;</code>
         */
        public com.google.protobuf.ByteString
        getNoofSavingDepositsBytes() {
            Object ref = noofSavingDeposits_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                noofSavingDeposits_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TOTALSAVINGDEPOSITAMOUNT_FIELD_NUMBER = 8;
        private volatile Object totalSavingDepositAmount_;

        /**
         * <code>string totalSavingDepositAmount = 8;</code>
         */
        public String getTotalSavingDepositAmount() {
            Object ref = totalSavingDepositAmount_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                totalSavingDepositAmount_ = s;
                return s;
            }
        }

        /**
         * <code>string totalSavingDepositAmount = 8;</code>
         */
        public com.google.protobuf.ByteString
        getTotalSavingDepositAmountBytes() {
            Object ref = totalSavingDepositAmount_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                totalSavingDepositAmount_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SERVICEID_FIELD_NUMBER = 9;
        private int serviceid_;

        /**
         * <code>int32 serviceid = 9;</code>
         */
        public int getServiceid() {
            return serviceid_;
        }

        public static final int SUBSERVICEID_FIELD_NUMBER = 10;
        private int subServiceid_;

        /**
         * <code>int32 subServiceid = 10;</code>
         */
        public int getSubServiceid() {
            return subServiceid_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getAgentNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, agentName_);
            }
            if (!getBranchNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, branchName_);
            }
            if (!getNoofDepositsBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, noofDeposits_);
            }
            if (!getTotalDepositAmountBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, totalDepositAmount_);
            }
            if (!getNoofLoanDepositsBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, noofLoanDeposits_);
            }
            if (!getTotalLoanDepositAmountBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, totalLoanDepositAmount_);
            }
            if (!getNoofSavingDepositsBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, noofSavingDeposits_);
            }
            if (!getTotalSavingDepositAmountBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, totalSavingDepositAmount_);
            }
            if (serviceid_ != 0) {
                output.writeInt32(9, serviceid_);
            }
            if (subServiceid_ != 0) {
                output.writeInt32(10, subServiceid_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getAgentNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, agentName_);
            }
            if (!getBranchNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, branchName_);
            }
            if (!getNoofDepositsBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, noofDeposits_);
            }
            if (!getTotalDepositAmountBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, totalDepositAmount_);
            }
            if (!getNoofLoanDepositsBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, noofLoanDeposits_);
            }
            if (!getTotalLoanDepositAmountBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, totalLoanDepositAmount_);
            }
            if (!getNoofSavingDepositsBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, noofSavingDeposits_);
            }
            if (!getTotalSavingDepositAmountBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, totalSavingDepositAmount_);
            }
            if (serviceid_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(9, serviceid_);
            }
            if (subServiceid_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(10, subServiceid_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary)) {
                return super.equals(obj);
            }
            com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary other = (com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary) obj;

            boolean result = true;
            result = result && getAgentName()
                    .equals(other.getAgentName());
            result = result && getBranchName()
                    .equals(other.getBranchName());
            result = result && getNoofDeposits()
                    .equals(other.getNoofDeposits());
            result = result && getTotalDepositAmount()
                    .equals(other.getTotalDepositAmount());
            result = result && getNoofLoanDeposits()
                    .equals(other.getNoofLoanDeposits());
            result = result && getTotalLoanDepositAmount()
                    .equals(other.getTotalLoanDepositAmount());
            result = result && getNoofSavingDeposits()
                    .equals(other.getNoofSavingDeposits());
            result = result && getTotalSavingDepositAmount()
                    .equals(other.getTotalSavingDepositAmount());
            result = result && (getServiceid()
                    == other.getServiceid());
            result = result && (getSubServiceid()
                    == other.getSubServiceid());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + AGENTNAME_FIELD_NUMBER;
            hash = (53 * hash) + getAgentName().hashCode();
            hash = (37 * hash) + BRANCHNAME_FIELD_NUMBER;
            hash = (53 * hash) + getBranchName().hashCode();
            hash = (37 * hash) + NOOFDEPOSITS_FIELD_NUMBER;
            hash = (53 * hash) + getNoofDeposits().hashCode();
            hash = (37 * hash) + TOTALDEPOSITAMOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getTotalDepositAmount().hashCode();
            hash = (37 * hash) + NOOFLOANDEPOSITS_FIELD_NUMBER;
            hash = (53 * hash) + getNoofLoanDeposits().hashCode();
            hash = (37 * hash) + TOTALLOANDEPOSITAMOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getTotalLoanDepositAmount().hashCode();
            hash = (37 * hash) + NOOFSAVINGDEPOSITS_FIELD_NUMBER;
            hash = (53 * hash) + getNoofSavingDeposits().hashCode();
            hash = (37 * hash) + TOTALSAVINGDEPOSITAMOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getTotalSavingDepositAmount().hashCode();
            hash = (37 * hash) + SERVICEID_FIELD_NUMBER;
            hash = (53 * hash) + getServiceid();
            hash = (37 * hash) + SUBSERVICEID_FIELD_NUMBER;
            hash = (53 * hash) + getSubServiceid();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.vcbl.tabbanking.protobuff.BCTxnSummary}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.vcbl.tabbanking.protobuff.BCTxnSummary)
                com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummaryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.class, com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.Builder.class);
            }

            // Construct using com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                agentName_ = "";

                branchName_ = "";

                noofDeposits_ = "";

                totalDepositAmount_ = "";

                noofLoanDeposits_ = "";

                totalLoanDepositAmount_ = "";

                noofSavingDeposits_ = "";

                totalSavingDepositAmount_ = "";

                serviceid_ = 0;

                subServiceid_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_descriptor;
            }

            public com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary getDefaultInstanceForType() {
                return com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.getDefaultInstance();
            }

            public com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary build() {
                com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary buildPartial() {
                com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary result = new com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary(this);
                result.agentName_ = agentName_;
                result.branchName_ = branchName_;
                result.noofDeposits_ = noofDeposits_;
                result.totalDepositAmount_ = totalDepositAmount_;
                result.noofLoanDeposits_ = noofLoanDeposits_;
                result.totalLoanDepositAmount_ = totalLoanDepositAmount_;
                result.noofSavingDeposits_ = noofSavingDeposits_;
                result.totalSavingDepositAmount_ = totalSavingDepositAmount_;
                result.serviceid_ = serviceid_;
                result.subServiceid_ = subServiceid_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary) {
                    return mergeFrom((com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary other) {
                if (other == com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary.getDefaultInstance())
                    return this;
                if (!other.getAgentName().isEmpty()) {
                    agentName_ = other.agentName_;
                    onChanged();
                }
                if (!other.getBranchName().isEmpty()) {
                    branchName_ = other.branchName_;
                    onChanged();
                }
                if (!other.getNoofDeposits().isEmpty()) {
                    noofDeposits_ = other.noofDeposits_;
                    onChanged();
                }
                if (!other.getTotalDepositAmount().isEmpty()) {
                    totalDepositAmount_ = other.totalDepositAmount_;
                    onChanged();
                }
                if (!other.getNoofLoanDeposits().isEmpty()) {
                    noofLoanDeposits_ = other.noofLoanDeposits_;
                    onChanged();
                }
                if (!other.getTotalLoanDepositAmount().isEmpty()) {
                    totalLoanDepositAmount_ = other.totalLoanDepositAmount_;
                    onChanged();
                }
                if (!other.getNoofSavingDeposits().isEmpty()) {
                    noofSavingDeposits_ = other.noofSavingDeposits_;
                    onChanged();
                }
                if (!other.getTotalSavingDepositAmount().isEmpty()) {
                    totalSavingDepositAmount_ = other.totalSavingDepositAmount_;
                    onChanged();
                }
                if (other.getServiceid() != 0) {
                    setServiceid(other.getServiceid());
                }
                if (other.getSubServiceid() != 0) {
                    setSubServiceid(other.getSubServiceid());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object agentName_ = "";

            /**
             * <code>string agentName = 1;</code>
             */
            public String getAgentName() {
                Object ref = agentName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    agentName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string agentName = 1;</code>
             */
            public com.google.protobuf.ByteString
            getAgentNameBytes() {
                Object ref = agentName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    agentName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string agentName = 1;</code>
             */
            public Builder setAgentName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                agentName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string agentName = 1;</code>
             */
            public Builder clearAgentName() {

                agentName_ = getDefaultInstance().getAgentName();
                onChanged();
                return this;
            }

            /**
             * <code>string agentName = 1;</code>
             */
            public Builder setAgentNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                agentName_ = value;
                onChanged();
                return this;
            }

            private Object branchName_ = "";

            /**
             * <code>string branchName = 2;</code>
             */
            public String getBranchName() {
                Object ref = branchName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    branchName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string branchName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getBranchNameBytes() {
                Object ref = branchName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    branchName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string branchName = 2;</code>
             */
            public Builder setBranchName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                branchName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string branchName = 2;</code>
             */
            public Builder clearBranchName() {

                branchName_ = getDefaultInstance().getBranchName();
                onChanged();
                return this;
            }

            /**
             * <code>string branchName = 2;</code>
             */
            public Builder setBranchNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                branchName_ = value;
                onChanged();
                return this;
            }

            private Object noofDeposits_ = "";

            /**
             * <code>string noofDeposits = 3;</code>
             */
            public String getNoofDeposits() {
                Object ref = noofDeposits_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    noofDeposits_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string noofDeposits = 3;</code>
             */
            public com.google.protobuf.ByteString
            getNoofDepositsBytes() {
                Object ref = noofDeposits_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    noofDeposits_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string noofDeposits = 3;</code>
             */
            public Builder setNoofDeposits(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                noofDeposits_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string noofDeposits = 3;</code>
             */
            public Builder clearNoofDeposits() {

                noofDeposits_ = getDefaultInstance().getNoofDeposits();
                onChanged();
                return this;
            }

            /**
             * <code>string noofDeposits = 3;</code>
             */
            public Builder setNoofDepositsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                noofDeposits_ = value;
                onChanged();
                return this;
            }

            private Object totalDepositAmount_ = "";

            /**
             * <code>string totalDepositAmount = 4;</code>
             */
            public String getTotalDepositAmount() {
                Object ref = totalDepositAmount_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    totalDepositAmount_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string totalDepositAmount = 4;</code>
             */
            public com.google.protobuf.ByteString
            getTotalDepositAmountBytes() {
                Object ref = totalDepositAmount_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    totalDepositAmount_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string totalDepositAmount = 4;</code>
             */
            public Builder setTotalDepositAmount(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                totalDepositAmount_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string totalDepositAmount = 4;</code>
             */
            public Builder clearTotalDepositAmount() {

                totalDepositAmount_ = getDefaultInstance().getTotalDepositAmount();
                onChanged();
                return this;
            }

            /**
             * <code>string totalDepositAmount = 4;</code>
             */
            public Builder setTotalDepositAmountBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                totalDepositAmount_ = value;
                onChanged();
                return this;
            }

            private Object noofLoanDeposits_ = "";

            /**
             * <code>string noofLoanDeposits = 5;</code>
             */
            public String getNoofLoanDeposits() {
                Object ref = noofLoanDeposits_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    noofLoanDeposits_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string noofLoanDeposits = 5;</code>
             */
            public com.google.protobuf.ByteString
            getNoofLoanDepositsBytes() {
                Object ref = noofLoanDeposits_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    noofLoanDeposits_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string noofLoanDeposits = 5;</code>
             */
            public Builder setNoofLoanDeposits(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                noofLoanDeposits_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string noofLoanDeposits = 5;</code>
             */
            public Builder clearNoofLoanDeposits() {

                noofLoanDeposits_ = getDefaultInstance().getNoofLoanDeposits();
                onChanged();
                return this;
            }

            /**
             * <code>string noofLoanDeposits = 5;</code>
             */
            public Builder setNoofLoanDepositsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                noofLoanDeposits_ = value;
                onChanged();
                return this;
            }

            private Object totalLoanDepositAmount_ = "";

            /**
             * <code>string totalLoanDepositAmount = 6;</code>
             */
            public String getTotalLoanDepositAmount() {
                Object ref = totalLoanDepositAmount_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    totalLoanDepositAmount_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string totalLoanDepositAmount = 6;</code>
             */
            public com.google.protobuf.ByteString
            getTotalLoanDepositAmountBytes() {
                Object ref = totalLoanDepositAmount_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    totalLoanDepositAmount_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string totalLoanDepositAmount = 6;</code>
             */
            public Builder setTotalLoanDepositAmount(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                totalLoanDepositAmount_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string totalLoanDepositAmount = 6;</code>
             */
            public Builder clearTotalLoanDepositAmount() {

                totalLoanDepositAmount_ = getDefaultInstance().getTotalLoanDepositAmount();
                onChanged();
                return this;
            }

            /**
             * <code>string totalLoanDepositAmount = 6;</code>
             */
            public Builder setTotalLoanDepositAmountBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                totalLoanDepositAmount_ = value;
                onChanged();
                return this;
            }

            private Object noofSavingDeposits_ = "";

            /**
             * <code>string noofSavingDeposits = 7;</code>
             */
            public String getNoofSavingDeposits() {
                Object ref = noofSavingDeposits_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    noofSavingDeposits_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string noofSavingDeposits = 7;</code>
             */
            public com.google.protobuf.ByteString
            getNoofSavingDepositsBytes() {
                Object ref = noofSavingDeposits_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    noofSavingDeposits_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string noofSavingDeposits = 7;</code>
             */
            public Builder setNoofSavingDeposits(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                noofSavingDeposits_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string noofSavingDeposits = 7;</code>
             */
            public Builder clearNoofSavingDeposits() {

                noofSavingDeposits_ = getDefaultInstance().getNoofSavingDeposits();
                onChanged();
                return this;
            }

            /**
             * <code>string noofSavingDeposits = 7;</code>
             */
            public Builder setNoofSavingDepositsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                noofSavingDeposits_ = value;
                onChanged();
                return this;
            }

            private Object totalSavingDepositAmount_ = "";

            /**
             * <code>string totalSavingDepositAmount = 8;</code>
             */
            public String getTotalSavingDepositAmount() {
                Object ref = totalSavingDepositAmount_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    totalSavingDepositAmount_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string totalSavingDepositAmount = 8;</code>
             */
            public com.google.protobuf.ByteString
            getTotalSavingDepositAmountBytes() {
                Object ref = totalSavingDepositAmount_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    totalSavingDepositAmount_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string totalSavingDepositAmount = 8;</code>
             */
            public Builder setTotalSavingDepositAmount(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                totalSavingDepositAmount_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string totalSavingDepositAmount = 8;</code>
             */
            public Builder clearTotalSavingDepositAmount() {

                totalSavingDepositAmount_ = getDefaultInstance().getTotalSavingDepositAmount();
                onChanged();
                return this;
            }

            /**
             * <code>string totalSavingDepositAmount = 8;</code>
             */
            public Builder setTotalSavingDepositAmountBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                totalSavingDepositAmount_ = value;
                onChanged();
                return this;
            }

            private int serviceid_;

            /**
             * <code>int32 serviceid = 9;</code>
             */
            public int getServiceid() {
                return serviceid_;
            }

            /**
             * <code>int32 serviceid = 9;</code>
             */
            public Builder setServiceid(int value) {

                serviceid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 serviceid = 9;</code>
             */
            public Builder clearServiceid() {

                serviceid_ = 0;
                onChanged();
                return this;
            }

            private int subServiceid_;

            /**
             * <code>int32 subServiceid = 10;</code>
             */
            public int getSubServiceid() {
                return subServiceid_;
            }

            /**
             * <code>int32 subServiceid = 10;</code>
             */
            public Builder setSubServiceid(int value) {

                subServiceid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 subServiceid = 10;</code>
             */
            public Builder clearSubServiceid() {

                subServiceid_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.vcbl.tabbanking.protobuff.BCTxnSummary)
        }

        // @@protoc_insertion_point(class_scope:com.vcbl.tabbanking.protobuff.BCTxnSummary)
        private static final com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary();
        }

        public static com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BCTxnSummary>
                PARSER = new com.google.protobuf.AbstractParser<BCTxnSummary>() {
            public BCTxnSummary parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BCTxnSummary(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<BCTxnSummary> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<BCTxnSummary> getParserForType() {
            return PARSER;
        }

        public com.vcbl.tabbanking.protobuff.BCTxnSummaryResponse.BCTxnSummary getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\032BCTxnSummaryResponse.proto\022\035com.vcbl.t" +
                        "abbanking.protobuff\"\210\002\n\014BCTxnSummary\022\021\n\t" +
                        "agentName\030\001 \001(\t\022\022\n\nbranchName\030\002 \001(\t\022\024\n\014n" +
                        "oofDeposits\030\003 \001(\t\022\032\n\022totalDepositAmount\030" +
                        "\004 \001(\t\022\030\n\020noofLoanDeposits\030\005 \001(\t\022\036\n\026total" +
                        "LoanDepositAmount\030\006 \001(\t\022\032\n\022noofSavingDep" +
                        "osits\030\007 \001(\t\022 \n\030totalSavingDepositAmount\030" +
                        "\010 \001(\t\022\021\n\tserviceid\030\t \001(\005\022\024\n\014subServiceid" +
                        "\030\n \001(\005b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_saranda_tabbanking_protobuff_BCTxnSummary_descriptor,
                new String[]{"AgentName", "BranchName", "NoofDeposits", "TotalDepositAmount", "NoofLoanDeposits", "TotalLoanDepositAmount", "NoofSavingDeposits", "TotalSavingDepositAmount", "Serviceid", "SubServiceid",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
