// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataSyncResponse.proto

package com.vcbl.tabbanking.protobuff;

public final class DataSyncResp {
  private DataSyncResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataSyncResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends: DataSyncResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appsVersion = 1;</code>
     */
    String getAppsVersion();
    /**
     * <code>string appsVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppsVersionBytes();

    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    String getTimeStamp();
    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>string microatmid = 3;</code>
     */
    String getMicroatmid();
    /**
     * <code>string microatmid = 3;</code>
     */
    com.google.protobuf.ByteString
        getMicroatmidBytes();

    /**
     * <code>. Status status = 4;</code>
     */
    int getStatusValue();
    /**
     * <code>. Status status = 4;</code>
     */
     Masters.Status getStatus();

    /**
     * <code>string statusDescription = 5;</code>
     */
    String getStatusDescription();
    /**
     * <code>string statusDescription = 5;</code>
     */
    com.google.protobuf.ByteString
        getStatusDescriptionBytes();

    /**
     * <code>repeated . Error errors = 6;</code>
     */
    java.util.List< Masters.Error> 
        getErrorsList();
    /**
     * <code>repeated . Error errors = 6;</code>
     */
     Masters.Error getErrors(int index);
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    int getErrorsCount();
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    java.util.List<? extends  Masters.ErrorOrBuilder> 
        getErrorsOrBuilderList();
    /**
     * <code>repeated . Error errors = 6;</code>
     */
     Masters.ErrorOrBuilder getErrorsOrBuilder(
            int index);

    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    java.util.List< Masters.NetworkSettings> 
        getNWSettingsList();
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
     Masters.NetworkSettings getNWSettings(int index);
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    int getNWSettingsCount();
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    java.util.List<? extends  Masters.NetworkSettingsOrBuilder> 
        getNWSettingsOrBuilderList();
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
     Masters.NetworkSettingsOrBuilder getNWSettingsOrBuilder(
            int index);

    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    java.util.List< Masters.BCMaster> 
        getBCMasterList();
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
     Masters.BCMaster getBCMaster(int index);
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    int getBCMasterCount();
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    java.util.List<? extends  Masters.BCMasterOrBuilder> 
        getBCMasterOrBuilderList();
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
     Masters.BCMasterOrBuilder getBCMasterOrBuilder(
            int index);

    /**
     * <code>repeated . Product Products = 9;</code>
     */
    java.util.List< Masters.Product> 
        getProductsList();
    /**
     * <code>repeated . Product Products = 9;</code>
     */
     Masters.Product getProducts(int index);
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    java.util.List<? extends  Masters.ProductOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated . Product Products = 9;</code>
     */
     Masters.ProductOrBuilder getProductsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code  DataSyncResponse}
   */
  public  static final class DataSyncResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements: DataSyncResponse)
      DataSyncResponseOrBuilder {
    // Use DataSyncResponse.newBuilder() to construct.
    private DataSyncResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataSyncResponse() {
      appsVersion_ = "";
      timeStamp_ = "";
      microatmid_ = "";
      status_ = 0;
      statusDescription_ = "";
      errors_ = java.util.Collections.emptyList();
      nWSettings_ = java.util.Collections.emptyList();
      bCMaster_ = java.util.Collections.emptyList();
      products_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DataSyncResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              appsVersion_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              timeStamp_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              microatmid_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              statusDescription_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                errors_ = new java.util.ArrayList< Masters.Error>();
                mutable_bitField0_ |= 0x00000020;
              }
              errors_.add(
                  input.readMessage( Masters.Error.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                nWSettings_ = new java.util.ArrayList< Masters.NetworkSettings>();
                mutable_bitField0_ |= 0x00000040;
              }
              nWSettings_.add(
                  input.readMessage( Masters.NetworkSettings.parser(), extensionRegistry));
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                bCMaster_ = new java.util.ArrayList< Masters.BCMaster>();
                mutable_bitField0_ |= 0x00000080;
              }
              bCMaster_.add(
                  input.readMessage( Masters.BCMaster.parser(), extensionRegistry));
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                products_ = new java.util.ArrayList< Masters.Product>();
                mutable_bitField0_ |= 0x00000100;
              }
              products_.add(
                  input.readMessage( Masters.Product.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          errors_ = java.util.Collections.unmodifiableList(errors_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          nWSettings_ = java.util.Collections.unmodifiableList(nWSettings_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          bCMaster_ = java.util.Collections.unmodifiableList(bCMaster_);
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          products_ = java.util.Collections.unmodifiableList(products_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return  DataSyncResp.internal_static_VCBL_DataSync_DataSyncResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return  DataSyncResp.internal_static_VCBL_DataSync_DataSyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
               DataSyncResp.DataSyncResponse.class,  DataSyncResp.DataSyncResponse.Builder.class);
    }

    private int bitField0_;
    public static final int APPSVERSION_FIELD_NUMBER = 1;
    private volatile Object appsVersion_;
    /**
     * <code>string appsVersion = 1;</code>
     */
    public String getAppsVersion() {
      Object ref = appsVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appsVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string appsVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppsVersionBytes() {
      Object ref = appsVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appsVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile Object timeStamp_;
    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    public String getTimeStamp() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *yyyy-mm-dd hh:mm:ss format
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MICROATMID_FIELD_NUMBER = 3;
    private volatile Object microatmid_;
    /**
     * <code>string microatmid = 3;</code>
     */
    public String getMicroatmid() {
      Object ref = microatmid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        microatmid_ = s;
        return s;
      }
    }
    /**
     * <code>string microatmid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMicroatmidBytes() {
      Object ref = microatmid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        microatmid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>. Status status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>. Status status = 4;</code>
     */
    public  Masters.Status getStatus() {
       Masters.Status result =  Masters.Status.valueOf(status_);
      return result == null ?  Masters.Status.UNRECOGNIZED : result;
    }

    public static final int STATUSDESCRIPTION_FIELD_NUMBER = 5;
    private volatile Object statusDescription_;
    /**
     * <code>string statusDescription = 5;</code>
     */
    public String getStatusDescription() {
      Object ref = statusDescription_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        statusDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string statusDescription = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStatusDescriptionBytes() {
      Object ref = statusDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        statusDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORS_FIELD_NUMBER = 6;
    private java.util.List< Masters.Error> errors_;
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    public java.util.List< Masters.Error> getErrorsList() {
      return errors_;
    }
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    public java.util.List<? extends  Masters.ErrorOrBuilder> 
        getErrorsOrBuilderList() {
      return errors_;
    }
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    public  Masters.Error getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated . Error errors = 6;</code>
     */
    public  Masters.ErrorOrBuilder getErrorsOrBuilder(
        int index) {
      return errors_.get(index);
    }

    public static final int NWSETTINGS_FIELD_NUMBER = 7;
    private java.util.List< Masters.NetworkSettings> nWSettings_;
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    public java.util.List< Masters.NetworkSettings> getNWSettingsList() {
      return nWSettings_;
    }
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    public java.util.List<? extends  Masters.NetworkSettingsOrBuilder> 
        getNWSettingsOrBuilderList() {
      return nWSettings_;
    }
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    public int getNWSettingsCount() {
      return nWSettings_.size();
    }
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    public  Masters.NetworkSettings getNWSettings(int index) {
      return nWSettings_.get(index);
    }
    /**
     * <code>repeated . NetworkSettings NWSettings = 7;</code>
     */
    public  Masters.NetworkSettingsOrBuilder getNWSettingsOrBuilder(
        int index) {
      return nWSettings_.get(index);
    }

    public static final int BCMASTER_FIELD_NUMBER = 8;
    private java.util.List< Masters.BCMaster> bCMaster_;
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    public java.util.List< Masters.BCMaster> getBCMasterList() {
      return bCMaster_;
    }
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    public java.util.List<? extends  Masters.BCMasterOrBuilder> 
        getBCMasterOrBuilderList() {
      return bCMaster_;
    }
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    public int getBCMasterCount() {
      return bCMaster_.size();
    }
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    public  Masters.BCMaster getBCMaster(int index) {
      return bCMaster_.get(index);
    }
    /**
     * <code>repeated . BCMaster BCMaster = 8;</code>
     */
    public  Masters.BCMasterOrBuilder getBCMasterOrBuilder(
        int index) {
      return bCMaster_.get(index);
    }

    public static final int PRODUCTS_FIELD_NUMBER = 9;
    private java.util.List< Masters.Product> products_;
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    public java.util.List< Masters.Product> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    public java.util.List<? extends  Masters.ProductOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    public  Masters.Product getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated . Product Products = 9;</code>
     */
    public  Masters.ProductOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppsVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appsVersion_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
      }
      if (!getMicroatmidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, microatmid_);
      }
      if (status_ !=  Masters.Status.SUCCESS.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (!getStatusDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, statusDescription_);
      }
      for (int i = 0; i < errors_.size(); i++) {
        output.writeMessage(6, errors_.get(i));
      }
      for (int i = 0; i < nWSettings_.size(); i++) {
        output.writeMessage(7, nWSettings_.get(i));
      }
      for (int i = 0; i < bCMaster_.size(); i++) {
        output.writeMessage(8, bCMaster_.get(i));
      }
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(9, products_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppsVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appsVersion_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
      }
      if (!getMicroatmidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, microatmid_);
      }
      if (status_ !=  Masters.Status.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (!getStatusDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, statusDescription_);
      }
      for (int i = 0; i < errors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, errors_.get(i));
      }
      for (int i = 0; i < nWSettings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, nWSettings_.get(i));
      }
      for (int i = 0; i < bCMaster_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, bCMaster_.get(i));
      }
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, products_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof  DataSyncResp.DataSyncResponse)) {
        return super.equals(obj);
      }
       DataSyncResp.DataSyncResponse other = ( DataSyncResp.DataSyncResponse) obj;

      boolean result = true;
      result = result && getAppsVersion()
          .equals(other.getAppsVersion());
      result = result && getTimeStamp()
          .equals(other.getTimeStamp());
      result = result && getMicroatmid()
          .equals(other.getMicroatmid());
      result = result && status_ == other.status_;
      result = result && getStatusDescription()
          .equals(other.getStatusDescription());
      result = result && getErrorsList()
          .equals(other.getErrorsList());
      result = result && getNWSettingsList()
          .equals(other.getNWSettingsList());
      result = result && getBCMasterList()
          .equals(other.getBCMasterList());
      result = result && getProductsList()
          .equals(other.getProductsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPSVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppsVersion().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (37 * hash) + MICROATMID_FIELD_NUMBER;
      hash = (53 * hash) + getMicroatmid().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + STATUSDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getStatusDescription().hashCode();
      if (getErrorsCount() > 0) {
        hash = (37 * hash) + ERRORS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorsList().hashCode();
      }
      if (getNWSettingsCount() > 0) {
        hash = (37 * hash) + NWSETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getNWSettingsList().hashCode();
      }
      if (getBCMasterCount() > 0) {
        hash = (37 * hash) + BCMASTER_FIELD_NUMBER;
        hash = (53 * hash) + getBCMasterList().hashCode();
      }
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static  DataSyncResp.DataSyncResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static  DataSyncResp.DataSyncResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static  DataSyncResp.DataSyncResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static  DataSyncResp.DataSyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder( DataSyncResp.DataSyncResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code  DataSyncResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements: DataSyncResponse)
         DataSyncResp.DataSyncResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  DataSyncResp.internal_static_VCBL_DataSync_DataSyncResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  DataSyncResp.internal_static_VCBL_DataSync_DataSyncResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                 DataSyncResp.DataSyncResponse.class,  DataSyncResp.DataSyncResponse.Builder.class);
      }

      // Construct using  DataSyncResp.DataSyncResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getErrorsFieldBuilder();
          getNWSettingsFieldBuilder();
          getBCMasterFieldBuilder();
          getProductsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        appsVersion_ = "";

        timeStamp_ = "";

        microatmid_ = "";

        status_ = 0;

        statusDescription_ = "";

        if (errorsBuilder_ == null) {
          errors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          errorsBuilder_.clear();
        }
        if (nWSettingsBuilder_ == null) {
          nWSettings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          nWSettingsBuilder_.clear();
        }
        if (bCMasterBuilder_ == null) {
          bCMaster_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          bCMasterBuilder_.clear();
        }
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          productsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  DataSyncResp.internal_static_VCBL_DataSync_DataSyncResponse_descriptor;
      }

      public  DataSyncResp.DataSyncResponse getDefaultInstanceForType() {
        return  DataSyncResp.DataSyncResponse.getDefaultInstance();
      }

      public  DataSyncResp.DataSyncResponse build() {
         DataSyncResp.DataSyncResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public  DataSyncResp.DataSyncResponse buildPartial() {
         DataSyncResp.DataSyncResponse result = new  DataSyncResp.DataSyncResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.appsVersion_ = appsVersion_;
        result.timeStamp_ = timeStamp_;
        result.microatmid_ = microatmid_;
        result.status_ = status_;
        result.statusDescription_ = statusDescription_;
        if (errorsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            errors_ = java.util.Collections.unmodifiableList(errors_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.errors_ = errors_;
        } else {
          result.errors_ = errorsBuilder_.build();
        }
        if (nWSettingsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            nWSettings_ = java.util.Collections.unmodifiableList(nWSettings_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.nWSettings_ = nWSettings_;
        } else {
          result.nWSettings_ = nWSettingsBuilder_.build();
        }
        if (bCMasterBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            bCMaster_ = java.util.Collections.unmodifiableList(bCMaster_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.bCMaster_ = bCMaster_;
        } else {
          result.bCMaster_ = bCMasterBuilder_.build();
        }
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof  DataSyncResp.DataSyncResponse) {
          return mergeFrom(( DataSyncResp.DataSyncResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom( DataSyncResp.DataSyncResponse other) {
        if (other ==  DataSyncResp.DataSyncResponse.getDefaultInstance()) return this;
        if (!other.getAppsVersion().isEmpty()) {
          appsVersion_ = other.appsVersion_;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (!other.getMicroatmid().isEmpty()) {
          microatmid_ = other.microatmid_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getStatusDescription().isEmpty()) {
          statusDescription_ = other.statusDescription_;
          onChanged();
        }
        if (errorsBuilder_ == null) {
          if (!other.errors_.isEmpty()) {
            if (errors_.isEmpty()) {
              errors_ = other.errors_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureErrorsIsMutable();
              errors_.addAll(other.errors_);
            }
            onChanged();
          }
        } else {
          if (!other.errors_.isEmpty()) {
            if (errorsBuilder_.isEmpty()) {
              errorsBuilder_.dispose();
              errorsBuilder_ = null;
              errors_ = other.errors_;
              bitField0_ = (bitField0_ & ~0x00000020);
              errorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getErrorsFieldBuilder() : null;
            } else {
              errorsBuilder_.addAllMessages(other.errors_);
            }
          }
        }
        if (nWSettingsBuilder_ == null) {
          if (!other.nWSettings_.isEmpty()) {
            if (nWSettings_.isEmpty()) {
              nWSettings_ = other.nWSettings_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureNWSettingsIsMutable();
              nWSettings_.addAll(other.nWSettings_);
            }
            onChanged();
          }
        } else {
          if (!other.nWSettings_.isEmpty()) {
            if (nWSettingsBuilder_.isEmpty()) {
              nWSettingsBuilder_.dispose();
              nWSettingsBuilder_ = null;
              nWSettings_ = other.nWSettings_;
              bitField0_ = (bitField0_ & ~0x00000040);
              nWSettingsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNWSettingsFieldBuilder() : null;
            } else {
              nWSettingsBuilder_.addAllMessages(other.nWSettings_);
            }
          }
        }
        if (bCMasterBuilder_ == null) {
          if (!other.bCMaster_.isEmpty()) {
            if (bCMaster_.isEmpty()) {
              bCMaster_ = other.bCMaster_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureBCMasterIsMutable();
              bCMaster_.addAll(other.bCMaster_);
            }
            onChanged();
          }
        } else {
          if (!other.bCMaster_.isEmpty()) {
            if (bCMasterBuilder_.isEmpty()) {
              bCMasterBuilder_.dispose();
              bCMasterBuilder_ = null;
              bCMaster_ = other.bCMaster_;
              bitField0_ = (bitField0_ & ~0x00000080);
              bCMasterBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBCMasterFieldBuilder() : null;
            } else {
              bCMasterBuilder_.addAllMessages(other.bCMaster_);
            }
          }
        }
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000100);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
         DataSyncResp.DataSyncResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = ( DataSyncResp.DataSyncResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object appsVersion_ = "";
      /**
       * <code>string appsVersion = 1;</code>
       */
      public String getAppsVersion() {
        Object ref = appsVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appsVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appsVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppsVersionBytes() {
        Object ref = appsVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appsVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appsVersion = 1;</code>
       */
      public Builder setAppsVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appsVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appsVersion = 1;</code>
       */
      public Builder clearAppsVersion() {
        
        appsVersion_ = getDefaultInstance().getAppsVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string appsVersion = 1;</code>
       */
      public Builder setAppsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appsVersion_ = value;
        onChanged();
        return this;
      }

      private Object timeStamp_ = "";
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public String getTimeStamp() {
        Object ref = timeStamp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public Builder setTimeStamp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *yyyy-mm-dd hh:mm:ss format
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private Object microatmid_ = "";
      /**
       * <code>string microatmid = 3;</code>
       */
      public String getMicroatmid() {
        Object ref = microatmid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          microatmid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string microatmid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMicroatmidBytes() {
        Object ref = microatmid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          microatmid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string microatmid = 3;</code>
       */
      public Builder setMicroatmid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        microatmid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string microatmid = 3;</code>
       */
      public Builder clearMicroatmid() {
        
        microatmid_ = getDefaultInstance().getMicroatmid();
        onChanged();
        return this;
      }
      /**
       * <code>string microatmid = 3;</code>
       */
      public Builder setMicroatmidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        microatmid_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>. Status status = 4;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>. Status status = 4;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>. Status status = 4;</code>
       */
      public  Masters.Status getStatus() {
         Masters.Status result =  Masters.Status.valueOf(status_);
        return result == null ?  Masters.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>. Status status = 4;</code>
       */
      public Builder setStatus( Masters.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>. Status status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object statusDescription_ = "";
      /**
       * <code>string statusDescription = 5;</code>
       */
      public String getStatusDescription() {
        Object ref = statusDescription_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          statusDescription_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStatusDescriptionBytes() {
        Object ref = statusDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          statusDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public Builder setStatusDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public Builder clearStatusDescription() {
        
        statusDescription_ = getDefaultInstance().getStatusDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public Builder setStatusDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusDescription_ = value;
        onChanged();
        return this;
      }

      private java.util.List< Masters.Error> errors_ =
        java.util.Collections.emptyList();
      private void ensureErrorsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          errors_ = new java.util.ArrayList< Masters.Error>(errors_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.Error,  Masters.Error.Builder,  Masters.ErrorOrBuilder> errorsBuilder_;

      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public java.util.List< Masters.Error> getErrorsList() {
        if (errorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(errors_);
        } else {
          return errorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public int getErrorsCount() {
        if (errorsBuilder_ == null) {
          return errors_.size();
        } else {
          return errorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public  Masters.Error getErrors(int index) {
        if (errorsBuilder_ == null) {
          return errors_.get(index);
        } else {
          return errorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder setErrors(
          int index,  Masters.Error value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.set(index, value);
          onChanged();
        } else {
          errorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder setErrors(
          int index,  Masters.Error.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.set(index, builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder addErrors( Masters.Error value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.add(value);
          onChanged();
        } else {
          errorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder addErrors(
          int index,  Masters.Error value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.add(index, value);
          onChanged();
        } else {
          errorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder addErrors(
           Masters.Error.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.add(builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder addErrors(
          int index,  Masters.Error.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.add(index, builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder addAllErrors(
          Iterable<? extends  Masters.Error> values) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, errors_);
          onChanged();
        } else {
          errorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder clearErrors() {
        if (errorsBuilder_ == null) {
          errors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          errorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public Builder removeErrors(int index) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.remove(index);
          onChanged();
        } else {
          errorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public  Masters.Error.Builder getErrorsBuilder(
          int index) {
        return getErrorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public  Masters.ErrorOrBuilder getErrorsOrBuilder(
          int index) {
        if (errorsBuilder_ == null) {
          return errors_.get(index);  } else {
          return errorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public java.util.List<? extends  Masters.ErrorOrBuilder> 
           getErrorsOrBuilderList() {
        if (errorsBuilder_ != null) {
          return errorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(errors_);
        }
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public  Masters.Error.Builder addErrorsBuilder() {
        return getErrorsFieldBuilder().addBuilder(
             Masters.Error.getDefaultInstance());
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public  Masters.Error.Builder addErrorsBuilder(
          int index) {
        return getErrorsFieldBuilder().addBuilder(
            index,  Masters.Error.getDefaultInstance());
      }
      /**
       * <code>repeated . Error errors = 6;</code>
       */
      public java.util.List< Masters.Error.Builder> 
           getErrorsBuilderList() {
        return getErrorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.Error,  Masters.Error.Builder,  Masters.ErrorOrBuilder> 
          getErrorsFieldBuilder() {
        if (errorsBuilder_ == null) {
          errorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
               Masters.Error,  Masters.Error.Builder,  Masters.ErrorOrBuilder>(
                  errors_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          errors_ = null;
        }
        return errorsBuilder_;
      }

      private java.util.List< Masters.NetworkSettings> nWSettings_ =
        java.util.Collections.emptyList();
      private void ensureNWSettingsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          nWSettings_ = new java.util.ArrayList< Masters.NetworkSettings>(nWSettings_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.NetworkSettings,  Masters.NetworkSettings.Builder,  Masters.NetworkSettingsOrBuilder> nWSettingsBuilder_;

      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public java.util.List< Masters.NetworkSettings> getNWSettingsList() {
        if (nWSettingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nWSettings_);
        } else {
          return nWSettingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public int getNWSettingsCount() {
        if (nWSettingsBuilder_ == null) {
          return nWSettings_.size();
        } else {
          return nWSettingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public  Masters.NetworkSettings getNWSettings(int index) {
        if (nWSettingsBuilder_ == null) {
          return nWSettings_.get(index);
        } else {
          return nWSettingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder setNWSettings(
          int index,  Masters.NetworkSettings value) {
        if (nWSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNWSettingsIsMutable();
          nWSettings_.set(index, value);
          onChanged();
        } else {
          nWSettingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder setNWSettings(
          int index,  Masters.NetworkSettings.Builder builderForValue) {
        if (nWSettingsBuilder_ == null) {
          ensureNWSettingsIsMutable();
          nWSettings_.set(index, builderForValue.build());
          onChanged();
        } else {
          nWSettingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder addNWSettings( Masters.NetworkSettings value) {
        if (nWSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNWSettingsIsMutable();
          nWSettings_.add(value);
          onChanged();
        } else {
          nWSettingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder addNWSettings(
          int index,  Masters.NetworkSettings value) {
        if (nWSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNWSettingsIsMutable();
          nWSettings_.add(index, value);
          onChanged();
        } else {
          nWSettingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder addNWSettings(
           Masters.NetworkSettings.Builder builderForValue) {
        if (nWSettingsBuilder_ == null) {
          ensureNWSettingsIsMutable();
          nWSettings_.add(builderForValue.build());
          onChanged();
        } else {
          nWSettingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder addNWSettings(
          int index,  Masters.NetworkSettings.Builder builderForValue) {
        if (nWSettingsBuilder_ == null) {
          ensureNWSettingsIsMutable();
          nWSettings_.add(index, builderForValue.build());
          onChanged();
        } else {
          nWSettingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder addAllNWSettings(
          Iterable<? extends  Masters.NetworkSettings> values) {
        if (nWSettingsBuilder_ == null) {
          ensureNWSettingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nWSettings_);
          onChanged();
        } else {
          nWSettingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder clearNWSettings() {
        if (nWSettingsBuilder_ == null) {
          nWSettings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          nWSettingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public Builder removeNWSettings(int index) {
        if (nWSettingsBuilder_ == null) {
          ensureNWSettingsIsMutable();
          nWSettings_.remove(index);
          onChanged();
        } else {
          nWSettingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public  Masters.NetworkSettings.Builder getNWSettingsBuilder(
          int index) {
        return getNWSettingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public  Masters.NetworkSettingsOrBuilder getNWSettingsOrBuilder(
          int index) {
        if (nWSettingsBuilder_ == null) {
          return nWSettings_.get(index);  } else {
          return nWSettingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public java.util.List<? extends  Masters.NetworkSettingsOrBuilder> 
           getNWSettingsOrBuilderList() {
        if (nWSettingsBuilder_ != null) {
          return nWSettingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nWSettings_);
        }
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public  Masters.NetworkSettings.Builder addNWSettingsBuilder() {
        return getNWSettingsFieldBuilder().addBuilder(
             Masters.NetworkSettings.getDefaultInstance());
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public  Masters.NetworkSettings.Builder addNWSettingsBuilder(
          int index) {
        return getNWSettingsFieldBuilder().addBuilder(
            index,  Masters.NetworkSettings.getDefaultInstance());
      }
      /**
       * <code>repeated . NetworkSettings NWSettings = 7;</code>
       */
      public java.util.List< Masters.NetworkSettings.Builder> 
           getNWSettingsBuilderList() {
        return getNWSettingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.NetworkSettings,  Masters.NetworkSettings.Builder,  Masters.NetworkSettingsOrBuilder> 
          getNWSettingsFieldBuilder() {
        if (nWSettingsBuilder_ == null) {
          nWSettingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
               Masters.NetworkSettings,  Masters.NetworkSettings.Builder,  Masters.NetworkSettingsOrBuilder>(
                  nWSettings_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          nWSettings_ = null;
        }
        return nWSettingsBuilder_;
      }

      private java.util.List< Masters.BCMaster> bCMaster_ =
        java.util.Collections.emptyList();
      private void ensureBCMasterIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          bCMaster_ = new java.util.ArrayList< Masters.BCMaster>(bCMaster_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.BCMaster,  Masters.BCMaster.Builder,  Masters.BCMasterOrBuilder> bCMasterBuilder_;

      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public java.util.List< Masters.BCMaster> getBCMasterList() {
        if (bCMasterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bCMaster_);
        } else {
          return bCMasterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public int getBCMasterCount() {
        if (bCMasterBuilder_ == null) {
          return bCMaster_.size();
        } else {
          return bCMasterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public  Masters.BCMaster getBCMaster(int index) {
        if (bCMasterBuilder_ == null) {
          return bCMaster_.get(index);
        } else {
          return bCMasterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder setBCMaster(
          int index,  Masters.BCMaster value) {
        if (bCMasterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBCMasterIsMutable();
          bCMaster_.set(index, value);
          onChanged();
        } else {
          bCMasterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder setBCMaster(
          int index,  Masters.BCMaster.Builder builderForValue) {
        if (bCMasterBuilder_ == null) {
          ensureBCMasterIsMutable();
          bCMaster_.set(index, builderForValue.build());
          onChanged();
        } else {
          bCMasterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder addBCMaster( Masters.BCMaster value) {
        if (bCMasterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBCMasterIsMutable();
          bCMaster_.add(value);
          onChanged();
        } else {
          bCMasterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder addBCMaster(
          int index,  Masters.BCMaster value) {
        if (bCMasterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBCMasterIsMutable();
          bCMaster_.add(index, value);
          onChanged();
        } else {
          bCMasterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder addBCMaster(
           Masters.BCMaster.Builder builderForValue) {
        if (bCMasterBuilder_ == null) {
          ensureBCMasterIsMutable();
          bCMaster_.add(builderForValue.build());
          onChanged();
        } else {
          bCMasterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder addBCMaster(
          int index,  Masters.BCMaster.Builder builderForValue) {
        if (bCMasterBuilder_ == null) {
          ensureBCMasterIsMutable();
          bCMaster_.add(index, builderForValue.build());
          onChanged();
        } else {
          bCMasterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder addAllBCMaster(
          Iterable<? extends  Masters.BCMaster> values) {
        if (bCMasterBuilder_ == null) {
          ensureBCMasterIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bCMaster_);
          onChanged();
        } else {
          bCMasterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder clearBCMaster() {
        if (bCMasterBuilder_ == null) {
          bCMaster_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          bCMasterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public Builder removeBCMaster(int index) {
        if (bCMasterBuilder_ == null) {
          ensureBCMasterIsMutable();
          bCMaster_.remove(index);
          onChanged();
        } else {
          bCMasterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public  Masters.BCMaster.Builder getBCMasterBuilder(
          int index) {
        return getBCMasterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public  Masters.BCMasterOrBuilder getBCMasterOrBuilder(
          int index) {
        if (bCMasterBuilder_ == null) {
          return bCMaster_.get(index);  } else {
          return bCMasterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public java.util.List<? extends  Masters.BCMasterOrBuilder> 
           getBCMasterOrBuilderList() {
        if (bCMasterBuilder_ != null) {
          return bCMasterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bCMaster_);
        }
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public  Masters.BCMaster.Builder addBCMasterBuilder() {
        return getBCMasterFieldBuilder().addBuilder(
             Masters.BCMaster.getDefaultInstance());
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public  Masters.BCMaster.Builder addBCMasterBuilder(
          int index) {
        return getBCMasterFieldBuilder().addBuilder(
            index,  Masters.BCMaster.getDefaultInstance());
      }
      /**
       * <code>repeated . BCMaster BCMaster = 8;</code>
       */
      public java.util.List< Masters.BCMaster.Builder> 
           getBCMasterBuilderList() {
        return getBCMasterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.BCMaster,  Masters.BCMaster.Builder,  Masters.BCMasterOrBuilder> 
          getBCMasterFieldBuilder() {
        if (bCMasterBuilder_ == null) {
          bCMasterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
               Masters.BCMaster,  Masters.BCMaster.Builder,  Masters.BCMasterOrBuilder>(
                  bCMaster_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          bCMaster_ = null;
        }
        return bCMasterBuilder_;
      }

      private java.util.List< Masters.Product> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          products_ = new java.util.ArrayList< Masters.Product>(products_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.Product,  Masters.Product.Builder,  Masters.ProductOrBuilder> productsBuilder_;

      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public java.util.List< Masters.Product> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public  Masters.Product getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder setProducts(
          int index,  Masters.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder setProducts(
          int index,  Masters.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder addProducts( Masters.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder addProducts(
          int index,  Masters.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder addProducts(
           Masters.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder addProducts(
          int index,  Masters.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder addAllProducts(
          Iterable<? extends  Masters.Product> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public  Masters.Product.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public  Masters.ProductOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public java.util.List<? extends  Masters.ProductOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public  Masters.Product.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
             Masters.Product.getDefaultInstance());
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public  Masters.Product.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index,  Masters.Product.getDefaultInstance());
      }
      /**
       * <code>repeated . Product Products = 9;</code>
       */
      public java.util.List< Masters.Product.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
           Masters.Product,  Masters.Product.Builder,  Masters.ProductOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
               Masters.Product,  Masters.Product.Builder,  Masters.ProductOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope: DataSyncResponse)
    }

    // @@protoc_insertion_point(class_scope: DataSyncResponse)
    private static final  DataSyncResp.DataSyncResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new  DataSyncResp.DataSyncResponse();
    }

    public static  DataSyncResp.DataSyncResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataSyncResponse>
        PARSER = new com.google.protobuf.AbstractParser<DataSyncResponse>() {
      public DataSyncResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataSyncResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataSyncResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DataSyncResponse> getParserForType() {
      return PARSER;
    }

    public  DataSyncResp.DataSyncResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VCBL_DataSync_DataSyncResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VCBL_DataSync_DataSyncResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026DataSyncResponse.proto\022\rVCBL.DataSync\032" +
      "\rMasters.proto\"\272\002\n\020DataSyncResponse\022\023\n\013a" +
      "ppsVersion\030\001 \001(\t\022\021\n\ttimeStamp\030\002 \001(\t\022\022\n\nm" +
      "icroatmid\030\003 \001(\t\022$\n\006status\030\004 \001(\0162\024.vcbl.m" +
      "asters.Status\022\031\n\021statusDescription\030\005 \001(\t" +
      "\022#\n\006errors\030\006 \003(\0132\023. Error\0221\n" +
      "\nNWSettings\030\007 \003(\0132\035. Network" +
      "Settings\022(\n\010BCMaster\030\010 \003(\0132\026.vcbl.master" +
      "s.BCMaster\022\'\n\010Products\030\t \003(\0132\025.vcbl.mast" +
      "ers.Productb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
           Masters.getDescriptor(),
        }, assigner);
    internal_static_VCBL_DataSync_DataSyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VCBL_DataSync_DataSyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VCBL_DataSync_DataSyncResponse_descriptor,
        new String[] { "AppsVersion", "TimeStamp", "Microatmid", "Status", "StatusDescription", "Errors", "NWSettings", "BCMaster", "Products", });
     Masters.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
