// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enrollmentuploadresponse.proto

package com.vcbl.tabbanking.protobuff;

public final class Enrollmentuploadresponse {
    private Enrollmentuploadresponse() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code com.vcbl.tabbanking.protobuff.Status}
     */
    public enum Status
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SUCCESS = 0;</code>
         */
        SUCCESS(0),
        /**
         * <code>FAILURE = 1;</code>
         */
        FAILURE(1),
        UNRECOGNIZED(-1),;

        /**
         * <code>SUCCESS = 0;</code>
         */
        public static final int SUCCESS_VALUE = 0;
        /**
         * <code>FAILURE = 1;</code>
         */
        public static final int FAILURE_VALUE = 1;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static Status valueOf(int value) {
            return forNumber(value);
        }

        public static Status forNumber(int value) {
            switch (value) {
                case 0:
                    return SUCCESS;
                case 1:
                    return FAILURE;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                Status> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<Status>() {
                    public Status findValueByNumber(int number) {
                        return Status.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return Enrollmentuploadresponse.getDescriptor().getEnumTypes().get(0);
        }

        private static final Status[] VALUES = values();

        public static Status valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private Status(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.vcbl.tabbanking.protobuff.Status)
    }

    public interface EnrolmentUploadResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string appVersion = 1;</code>
         */
        String getAppVersion();

        /**
         * <code>string appVersion = 1;</code>
         */
        com.google.protobuf.ByteString
        getAppVersionBytes();

        /**
         * <pre>
         * yyyy-mm-dd hh:mm:ss format
         * </pre>
         * <p>
         * <code>string timeStamp = 2;</code>
         */
        String getTimeStamp();

        /**
         * <pre>
         * yyyy-mm-dd hh:mm:ss format
         * </pre>
         * <p>
         * <code>string timeStamp = 2;</code>
         */
        com.google.protobuf.ByteString
        getTimeStampBytes();

        /**
         * <pre>
         * 0 Success else Failure
         * </pre>
         * <p>
         * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
         */
        int getStatusValue();

        /**
         * <pre>
         * 0 Success else Failure
         * </pre>
         * <p>
         * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
         */
        Status getStatus();

        /**
         * <pre>
         * Success if status ==0 else Failure Message
         * </pre>
         * <p>
         * <code>string statusDescription = 4;</code>
         */
        String getStatusDescription();

        /**
         * <pre>
         * Success if status ==0 else Failure Message
         * </pre>
         * <p>
         * <code>string statusDescription = 4;</code>
         */
        com.google.protobuf.ByteString
        getStatusDescriptionBytes();
    }

    /**
     * Protobuf type {@code com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse}
     */
    public static final class EnrolmentUploadResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse)
            EnrolmentUploadResponseOrBuilder {
        // Use EnrolmentUploadResponse.newBuilder() to construct.
        private EnrolmentUploadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private EnrolmentUploadResponse() {
            appVersion_ = "";
            timeStamp_ = "";
            status_ = 0;
            statusDescription_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private EnrolmentUploadResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            appVersion_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            timeStamp_ = s;
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            status_ = rawValue;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            statusDescription_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Enrollmentuploadresponse.internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Enrollmentuploadresponse.internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            EnrolmentUploadResponse.class, Builder.class);
        }

        public static final int APPVERSION_FIELD_NUMBER = 1;
        private volatile Object appVersion_;

        /**
         * <code>string appVersion = 1;</code>
         */
        public String getAppVersion() {
            Object ref = appVersion_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                appVersion_ = s;
                return s;
            }
        }

        /**
         * <code>string appVersion = 1;</code>
         */
        public com.google.protobuf.ByteString
        getAppVersionBytes() {
            Object ref = appVersion_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                appVersion_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 2;
        private volatile Object timeStamp_;

        /**
         * <pre>
         * yyyy-mm-dd hh:mm:ss format
         * </pre>
         * <p>
         * <code>string timeStamp = 2;</code>
         */
        public String getTimeStamp() {
            Object ref = timeStamp_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                timeStamp_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * yyyy-mm-dd hh:mm:ss format
         * </pre>
         * <p>
         * <code>string timeStamp = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTimeStampBytes() {
            Object ref = timeStamp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                timeStamp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int STATUS_FIELD_NUMBER = 3;
        private int status_;

        /**
         * <pre>
         * 0 Success else Failure
         * </pre>
         * <p>
         * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
         */
        public int getStatusValue() {
            return status_;
        }

        /**
         * <pre>
         * 0 Success else Failure
         * </pre>
         * <p>
         * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
         */
        public Status getStatus() {
            Status result = Status.valueOf(status_);
            return result == null ? Status.UNRECOGNIZED : result;
        }

        public static final int STATUSDESCRIPTION_FIELD_NUMBER = 4;
        private volatile Object statusDescription_;

        /**
         * <pre>
         * Success if status ==0 else Failure Message
         * </pre>
         * <p>
         * <code>string statusDescription = 4;</code>
         */
        public String getStatusDescription() {
            Object ref = statusDescription_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                statusDescription_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Success if status ==0 else Failure Message
         * </pre>
         * <p>
         * <code>string statusDescription = 4;</code>
         */
        public com.google.protobuf.ByteString
        getStatusDescriptionBytes() {
            Object ref = statusDescription_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                statusDescription_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getAppVersionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appVersion_);
            }
            if (!getTimeStampBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
            }
            if (status_ != Status.SUCCESS.getNumber()) {
                output.writeEnum(3, status_);
            }
            if (!getStatusDescriptionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, statusDescription_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getAppVersionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appVersion_);
            }
            if (!getTimeStampBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
            }
            if (status_ != Status.SUCCESS.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, status_);
            }
            if (!getStatusDescriptionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, statusDescription_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof EnrolmentUploadResponse)) {
                return super.equals(obj);
            }
            EnrolmentUploadResponse other = (EnrolmentUploadResponse) obj;

            boolean result = true;
            result = result && getAppVersion()
                    .equals(other.getAppVersion());
            result = result && getTimeStamp()
                    .equals(other.getTimeStamp());
            result = result && status_ == other.status_;
            result = result && getStatusDescription()
                    .equals(other.getStatusDescription());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
            hash = (53 * hash) + getAppVersion().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + getTimeStamp().hashCode();
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + status_;
            hash = (37 * hash) + STATUSDESCRIPTION_FIELD_NUMBER;
            hash = (53 * hash) + getStatusDescription().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static EnrolmentUploadResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EnrolmentUploadResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EnrolmentUploadResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EnrolmentUploadResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EnrolmentUploadResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static EnrolmentUploadResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static EnrolmentUploadResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static EnrolmentUploadResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static EnrolmentUploadResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static EnrolmentUploadResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(EnrolmentUploadResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse)
                EnrolmentUploadResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Enrollmentuploadresponse.internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Enrollmentuploadresponse.internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                EnrolmentUploadResponse.class, Builder.class);
            }

            // Construct using com.vcbl.tabbanking.protobuff.Enrollmentuploadresponse.EnrolmentUploadResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                appVersion_ = "";

                timeStamp_ = "";

                status_ = 0;

                statusDescription_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Enrollmentuploadresponse.internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_descriptor;
            }

            public EnrolmentUploadResponse getDefaultInstanceForType() {
                return EnrolmentUploadResponse.getDefaultInstance();
            }

            public EnrolmentUploadResponse build() {
                EnrolmentUploadResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public EnrolmentUploadResponse buildPartial() {
                EnrolmentUploadResponse result = new EnrolmentUploadResponse(this);
                result.appVersion_ = appVersion_;
                result.timeStamp_ = timeStamp_;
                result.status_ = status_;
                result.statusDescription_ = statusDescription_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof EnrolmentUploadResponse) {
                    return mergeFrom((EnrolmentUploadResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(EnrolmentUploadResponse other) {
                if (other == EnrolmentUploadResponse.getDefaultInstance()) return this;
                if (!other.getAppVersion().isEmpty()) {
                    appVersion_ = other.appVersion_;
                    onChanged();
                }
                if (!other.getTimeStamp().isEmpty()) {
                    timeStamp_ = other.timeStamp_;
                    onChanged();
                }
                if (other.status_ != 0) {
                    setStatusValue(other.getStatusValue());
                }
                if (!other.getStatusDescription().isEmpty()) {
                    statusDescription_ = other.statusDescription_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                EnrolmentUploadResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (EnrolmentUploadResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object appVersion_ = "";

            /**
             * <code>string appVersion = 1;</code>
             */
            public String getAppVersion() {
                Object ref = appVersion_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    appVersion_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string appVersion = 1;</code>
             */
            public com.google.protobuf.ByteString
            getAppVersionBytes() {
                Object ref = appVersion_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    appVersion_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string appVersion = 1;</code>
             */
            public Builder setAppVersion(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                appVersion_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string appVersion = 1;</code>
             */
            public Builder clearAppVersion() {

                appVersion_ = getDefaultInstance().getAppVersion();
                onChanged();
                return this;
            }

            /**
             * <code>string appVersion = 1;</code>
             */
            public Builder setAppVersionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                appVersion_ = value;
                onChanged();
                return this;
            }

            private Object timeStamp_ = "";

            /**
             * <pre>
             * yyyy-mm-dd hh:mm:ss format
             * </pre>
             * <p>
             * <code>string timeStamp = 2;</code>
             */
            public String getTimeStamp() {
                Object ref = timeStamp_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    timeStamp_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * yyyy-mm-dd hh:mm:ss format
             * </pre>
             * <p>
             * <code>string timeStamp = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTimeStampBytes() {
                Object ref = timeStamp_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    timeStamp_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * yyyy-mm-dd hh:mm:ss format
             * </pre>
             * <p>
             * <code>string timeStamp = 2;</code>
             */
            public Builder setTimeStamp(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                timeStamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * yyyy-mm-dd hh:mm:ss format
             * </pre>
             * <p>
             * <code>string timeStamp = 2;</code>
             */
            public Builder clearTimeStamp() {

                timeStamp_ = getDefaultInstance().getTimeStamp();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * yyyy-mm-dd hh:mm:ss format
             * </pre>
             * <p>
             * <code>string timeStamp = 2;</code>
             */
            public Builder setTimeStampBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                timeStamp_ = value;
                onChanged();
                return this;
            }

            private int status_ = 0;

            /**
             * <pre>
             * 0 Success else Failure
             * </pre>
             * <p>
             * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
             */
            public int getStatusValue() {
                return status_;
            }

            /**
             * <pre>
             * 0 Success else Failure
             * </pre>
             * <p>
             * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
             */
            public Builder setStatusValue(int value) {
                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 0 Success else Failure
             * </pre>
             * <p>
             * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
             */
            public Status getStatus() {
                Status result = Status.valueOf(status_);
                return result == null ? Status.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * 0 Success else Failure
             * </pre>
             * <p>
             * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
             */
            public Builder setStatus(Status value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                status_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 0 Success else Failure
             * </pre>
             * <p>
             * <code>.com.vcbl.tabbanking.protobuff.Status status = 3;</code>
             */
            public Builder clearStatus() {

                status_ = 0;
                onChanged();
                return this;
            }

            private Object statusDescription_ = "";

            /**
             * <pre>
             * Success if status ==0 else Failure Message
             * </pre>
             * <p>
             * <code>string statusDescription = 4;</code>
             */
            public String getStatusDescription() {
                Object ref = statusDescription_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    statusDescription_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * Success if status ==0 else Failure Message
             * </pre>
             * <p>
             * <code>string statusDescription = 4;</code>
             */
            public com.google.protobuf.ByteString
            getStatusDescriptionBytes() {
                Object ref = statusDescription_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    statusDescription_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Success if status ==0 else Failure Message
             * </pre>
             * <p>
             * <code>string statusDescription = 4;</code>
             */
            public Builder setStatusDescription(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                statusDescription_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Success if status ==0 else Failure Message
             * </pre>
             * <p>
             * <code>string statusDescription = 4;</code>
             */
            public Builder clearStatusDescription() {

                statusDescription_ = getDefaultInstance().getStatusDescription();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Success if status ==0 else Failure Message
             * </pre>
             * <p>
             * <code>string statusDescription = 4;</code>
             */
            public Builder setStatusDescriptionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                statusDescription_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse)
        }

        // @@protoc_insertion_point(class_scope:com.vcbl.tabbanking.protobuff.EnrolmentUploadResponse)
        private static final EnrolmentUploadResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new EnrolmentUploadResponse();
        }

        public static EnrolmentUploadResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<EnrolmentUploadResponse>
                PARSER = new com.google.protobuf.AbstractParser<EnrolmentUploadResponse>() {
            public EnrolmentUploadResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new EnrolmentUploadResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<EnrolmentUploadResponse> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<EnrolmentUploadResponse> getParserForType() {
            return PARSER;
        }

        public EnrolmentUploadResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\036enrollmentuploadresponse.proto\022\035com.vc" +
                        "bl.tabbanking.protobuff\"\222\001\n\027EnrolmentUpl" +
                        "oadResponse\022\022\n\nappVersion\030\001 \001(\t\022\021\n\ttimeS" +
                        "tamp\030\002 \001(\t\0225\n\006status\030\003 \001(\0162%.com.vcbl.ta" +
                        "bbanking.protobuff.Status\022\031\n\021statusDescr" +
                        "iption\030\004 \001(\t*\"\n\006Status\022\013\n\007SUCCESS\020\000\022\013\n\007F" +
                        "AILURE\020\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_vcbl_tabbanking_protobuff_EnrolmentUploadResponse_descriptor,
                new String[]{"AppVersion", "TimeStamp", "Status", "StatusDescription",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
