// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoandetailsProto.proto

package com.vcbl.tabbanking.protobuff;

public final class LoandetailsProto {
  private LoandetailsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoanDetailsProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:  LoanDetailsProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 agentid = 1;</code>
     */
    int getAgentid();

    /**
     * <code>int32 microatmid = 2;</code>
     */
    int getMicroatmid();

    /**
     * <code>int32 branchid = 3;</code>
     */
    int getBranchid();

    /**
     * <code>string branchcode = 4;</code>
     */
    java.lang.String getBranchcode();
    /**
     * <code>string branchcode = 4;</code>
     */
    com.google.protobuf.ByteString
        getBranchcodeBytes();

    /**
     * <code>string AccountNo = 5;</code>
     */
    java.lang.String getAccountNo();
    /**
     * <code>string AccountNo = 5;</code>
     */
    com.google.protobuf.ByteString
        getAccountNoBytes();

    /**
     * <code>string CustName = 6;</code>
     */
    java.lang.String getCustName();
    /**
     * <code>string CustName = 6;</code>
     */
    com.google.protobuf.ByteString
        getCustNameBytes();

    /**
     * <code>string ScanctionAmount = 7;</code>
     */
    java.lang.String getScanctionAmount();
    /**
     * <code>string ScanctionAmount = 7;</code>
     */
    com.google.protobuf.ByteString
        getScanctionAmountBytes();

    /**
     * <code>string Scanctiondt = 8;</code>
     */
    java.lang.String getScanctiondt();
    /**
     * <code>string Scanctiondt = 8;</code>
     */
    com.google.protobuf.ByteString
        getScanctiondtBytes();

    /**
     * <code>string InstallmentAmt = 9;</code>
     */
    java.lang.String getInstallmentAmt();
    /**
     * <code>string InstallmentAmt = 9;</code>
     */
    com.google.protobuf.ByteString
        getInstallmentAmtBytes();

    /**
     * <code>int32 Noofinstallments = 10;</code>
     */
    int getNoofinstallments();

    /**
     * <code>string OutstandingBal = 11;</code>
     */
    java.lang.String getOutstandingBal();
    /**
     * <code>string OutstandingBal = 11;</code>
     */
    com.google.protobuf.ByteString
        getOutstandingBalBytes();

    /**
     * <code>string Expirydate = 12;</code>
     */
    java.lang.String getExpirydate();
    /**
     * <code>string Expirydate = 12;</code>
     */
    com.google.protobuf.ByteString
        getExpirydateBytes();

    /**
     * <code>string Overdue = 13;</code>
     */
    java.lang.String getOverdue();
    /**
     * <code>string Overdue = 13;</code>
     */
    com.google.protobuf.ByteString
        getOverdueBytes();

    /**
     * <code>int32 pendingInstlmnts = 14;</code>
     */
    int getPendingInstlmnts();

    /**
     * <code>string txndate = 15;</code>
     */
    java.lang.String getTxndate();
    /**
     * <code>string txndate = 15;</code>
     */
    com.google.protobuf.ByteString
        getTxndateBytes();

    /**
     * <code>string txnStatus = 16;</code>
     */
    java.lang.String getTxnStatus();
    /**
     * <code>string txnStatus = 16;</code>
     */
    com.google.protobuf.ByteString
        getTxnStatusBytes();

    /**
     * <code>string reserve1 = 17;</code>
     */
    java.lang.String getReserve1();
    /**
     * <code>string reserve1 = 17;</code>
     */
    com.google.protobuf.ByteString
        getReserve1Bytes();

    /**
     * <code>string reserve2 = 18;</code>
     */
    java.lang.String getReserve2();
    /**
     * <code>string reserve2 = 18;</code>
     */
    com.google.protobuf.ByteString
        getReserve2Bytes();

    /**
     * <code>string reserve3 = 19;</code>
     */
    java.lang.String getReserve3();
    /**
     * <code>string reserve3 = 19;</code>
     */
    com.google.protobuf.ByteString
        getReserve3Bytes();
  }
  /**
   * Protobuf type {@code   LoanDetailsProto}
   */
  public  static final class LoanDetailsProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:  LoanDetailsProto)
      LoanDetailsProtoOrBuilder {
    // Use LoanDetailsProto.newBuilder() to construct.
    private LoanDetailsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoanDetailsProto() {
      agentid_ = 0;
      microatmid_ = 0;
      branchid_ = 0;
      branchcode_ = "";
      accountNo_ = "";
      custName_ = "";
      scanctionAmount_ = "";
      scanctiondt_ = "";
      installmentAmt_ = "";
      noofinstallments_ = 0;
      outstandingBal_ = "";
      expirydate_ = "";
      overdue_ = "";
      pendingInstlmnts_ = 0;
      txndate_ = "";
      txnStatus_ = "";
      reserve1_ = "";
      reserve2_ = "";
      reserve3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoanDetailsProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              agentid_ = input.readInt32();
              break;
            }
            case 16: {

              microatmid_ = input.readInt32();
              break;
            }
            case 24: {

              branchid_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              branchcode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              accountNo_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              custName_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              scanctionAmount_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              scanctiondt_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              installmentAmt_ = s;
              break;
            }
            case 80: {

              noofinstallments_ = input.readInt32();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              outstandingBal_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              expirydate_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              overdue_ = s;
              break;
            }
            case 112: {

              pendingInstlmnts_ = input.readInt32();
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              txndate_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              txnStatus_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              reserve1_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              reserve2_ = s;
              break;
            }
            case 154: {
              java.lang.String s = input.readStringRequireUtf8();

              reserve3_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return   LoandetailsProto.internal_static_VCBL_Transaction_LoanDetailsProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return   LoandetailsProto.internal_static_VCBL_Transaction_LoanDetailsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                LoandetailsProto.LoanDetailsProto.class,   LoandetailsProto.LoanDetailsProto.Builder.class);
    }

    public static final int AGENTID_FIELD_NUMBER = 1;
    private int agentid_;
    /**
     * <code>int32 agentid = 1;</code>
     */
    public int getAgentid() {
      return agentid_;
    }

    public static final int MICROATMID_FIELD_NUMBER = 2;
    private int microatmid_;
    /**
     * <code>int32 microatmid = 2;</code>
     */
    public int getMicroatmid() {
      return microatmid_;
    }

    public static final int BRANCHID_FIELD_NUMBER = 3;
    private int branchid_;
    /**
     * <code>int32 branchid = 3;</code>
     */
    public int getBranchid() {
      return branchid_;
    }

    public static final int BRANCHCODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object branchcode_;
    /**
     * <code>string branchcode = 4;</code>
     */
    public java.lang.String getBranchcode() {
      java.lang.Object ref = branchcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        branchcode_ = s;
        return s;
      }
    }
    /**
     * <code>string branchcode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBranchcodeBytes() {
      java.lang.Object ref = branchcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        branchcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTNO_FIELD_NUMBER = 5;
    private volatile java.lang.Object accountNo_;
    /**
     * <code>string AccountNo = 5;</code>
     */
    public java.lang.String getAccountNo() {
      java.lang.Object ref = accountNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNo_ = s;
        return s;
      }
    }
    /**
     * <code>string AccountNo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNoBytes() {
      java.lang.Object ref = accountNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object custName_;
    /**
     * <code>string CustName = 6;</code>
     */
    public java.lang.String getCustName() {
      java.lang.Object ref = custName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        custName_ = s;
        return s;
      }
    }
    /**
     * <code>string CustName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCustNameBytes() {
      java.lang.Object ref = custName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        custName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCANCTIONAMOUNT_FIELD_NUMBER = 7;
    private volatile java.lang.Object scanctionAmount_;
    /**
     * <code>string ScanctionAmount = 7;</code>
     */
    public java.lang.String getScanctionAmount() {
      java.lang.Object ref = scanctionAmount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scanctionAmount_ = s;
        return s;
      }
    }
    /**
     * <code>string ScanctionAmount = 7;</code>
     */
    public com.google.protobuf.ByteString
        getScanctionAmountBytes() {
      java.lang.Object ref = scanctionAmount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scanctionAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCANCTIONDT_FIELD_NUMBER = 8;
    private volatile java.lang.Object scanctiondt_;
    /**
     * <code>string Scanctiondt = 8;</code>
     */
    public java.lang.String getScanctiondt() {
      java.lang.Object ref = scanctiondt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scanctiondt_ = s;
        return s;
      }
    }
    /**
     * <code>string Scanctiondt = 8;</code>
     */
    public com.google.protobuf.ByteString
        getScanctiondtBytes() {
      java.lang.Object ref = scanctiondt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scanctiondt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTALLMENTAMT_FIELD_NUMBER = 9;
    private volatile java.lang.Object installmentAmt_;
    /**
     * <code>string InstallmentAmt = 9;</code>
     */
    public java.lang.String getInstallmentAmt() {
      java.lang.Object ref = installmentAmt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        installmentAmt_ = s;
        return s;
      }
    }
    /**
     * <code>string InstallmentAmt = 9;</code>
     */
    public com.google.protobuf.ByteString
        getInstallmentAmtBytes() {
      java.lang.Object ref = installmentAmt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        installmentAmt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOOFINSTALLMENTS_FIELD_NUMBER = 10;
    private int noofinstallments_;
    /**
     * <code>int32 Noofinstallments = 10;</code>
     */
    public int getNoofinstallments() {
      return noofinstallments_;
    }

    public static final int OUTSTANDINGBAL_FIELD_NUMBER = 11;
    private volatile java.lang.Object outstandingBal_;
    /**
     * <code>string OutstandingBal = 11;</code>
     */
    public java.lang.String getOutstandingBal() {
      java.lang.Object ref = outstandingBal_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outstandingBal_ = s;
        return s;
      }
    }
    /**
     * <code>string OutstandingBal = 11;</code>
     */
    public com.google.protobuf.ByteString
        getOutstandingBalBytes() {
      java.lang.Object ref = outstandingBal_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outstandingBal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRYDATE_FIELD_NUMBER = 12;
    private volatile java.lang.Object expirydate_;
    /**
     * <code>string Expirydate = 12;</code>
     */
    public java.lang.String getExpirydate() {
      java.lang.Object ref = expirydate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expirydate_ = s;
        return s;
      }
    }
    /**
     * <code>string Expirydate = 12;</code>
     */
    public com.google.protobuf.ByteString
        getExpirydateBytes() {
      java.lang.Object ref = expirydate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expirydate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OVERDUE_FIELD_NUMBER = 13;
    private volatile java.lang.Object overdue_;
    /**
     * <code>string Overdue = 13;</code>
     */
    public java.lang.String getOverdue() {
      java.lang.Object ref = overdue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        overdue_ = s;
        return s;
      }
    }
    /**
     * <code>string Overdue = 13;</code>
     */
    public com.google.protobuf.ByteString
        getOverdueBytes() {
      java.lang.Object ref = overdue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        overdue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PENDINGINSTLMNTS_FIELD_NUMBER = 14;
    private int pendingInstlmnts_;
    /**
     * <code>int32 pendingInstlmnts = 14;</code>
     */
    public int getPendingInstlmnts() {
      return pendingInstlmnts_;
    }

    public static final int TXNDATE_FIELD_NUMBER = 15;
    private volatile java.lang.Object txndate_;
    /**
     * <code>string txndate = 15;</code>
     */
    public java.lang.String getTxndate() {
      java.lang.Object ref = txndate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txndate_ = s;
        return s;
      }
    }
    /**
     * <code>string txndate = 15;</code>
     */
    public com.google.protobuf.ByteString
        getTxndateBytes() {
      java.lang.Object ref = txndate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txndate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXNSTATUS_FIELD_NUMBER = 16;
    private volatile java.lang.Object txnStatus_;
    /**
     * <code>string txnStatus = 16;</code>
     */
    public java.lang.String getTxnStatus() {
      java.lang.Object ref = txnStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txnStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string txnStatus = 16;</code>
     */
    public com.google.protobuf.ByteString
        getTxnStatusBytes() {
      java.lang.Object ref = txnStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESERVE1_FIELD_NUMBER = 17;
    private volatile java.lang.Object reserve1_;
    /**
     * <code>string reserve1 = 17;</code>
     */
    public java.lang.String getReserve1() {
      java.lang.Object ref = reserve1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reserve1_ = s;
        return s;
      }
    }
    /**
     * <code>string reserve1 = 17;</code>
     */
    public com.google.protobuf.ByteString
        getReserve1Bytes() {
      java.lang.Object ref = reserve1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reserve1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESERVE2_FIELD_NUMBER = 18;
    private volatile java.lang.Object reserve2_;
    /**
     * <code>string reserve2 = 18;</code>
     */
    public java.lang.String getReserve2() {
      java.lang.Object ref = reserve2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reserve2_ = s;
        return s;
      }
    }
    /**
     * <code>string reserve2 = 18;</code>
     */
    public com.google.protobuf.ByteString
        getReserve2Bytes() {
      java.lang.Object ref = reserve2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reserve2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESERVE3_FIELD_NUMBER = 19;
    private volatile java.lang.Object reserve3_;
    /**
     * <code>string reserve3 = 19;</code>
     */
    public java.lang.String getReserve3() {
      java.lang.Object ref = reserve3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reserve3_ = s;
        return s;
      }
    }
    /**
     * <code>string reserve3 = 19;</code>
     */
    public com.google.protobuf.ByteString
        getReserve3Bytes() {
      java.lang.Object ref = reserve3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reserve3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (agentid_ != 0) {
        output.writeInt32(1, agentid_);
      }
      if (microatmid_ != 0) {
        output.writeInt32(2, microatmid_);
      }
      if (branchid_ != 0) {
        output.writeInt32(3, branchid_);
      }
      if (!getBranchcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, branchcode_);
      }
      if (!getAccountNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, accountNo_);
      }
      if (!getCustNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, custName_);
      }
      if (!getScanctionAmountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, scanctionAmount_);
      }
      if (!getScanctiondtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, scanctiondt_);
      }
      if (!getInstallmentAmtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, installmentAmt_);
      }
      if (noofinstallments_ != 0) {
        output.writeInt32(10, noofinstallments_);
      }
      if (!getOutstandingBalBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, outstandingBal_);
      }
      if (!getExpirydateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, expirydate_);
      }
      if (!getOverdueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, overdue_);
      }
      if (pendingInstlmnts_ != 0) {
        output.writeInt32(14, pendingInstlmnts_);
      }
      if (!getTxndateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, txndate_);
      }
      if (!getTxnStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, txnStatus_);
      }
      if (!getReserve1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, reserve1_);
      }
      if (!getReserve2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, reserve2_);
      }
      if (!getReserve3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, reserve3_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (agentid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agentid_);
      }
      if (microatmid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, microatmid_);
      }
      if (branchid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, branchid_);
      }
      if (!getBranchcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, branchcode_);
      }
      if (!getAccountNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, accountNo_);
      }
      if (!getCustNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, custName_);
      }
      if (!getScanctionAmountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, scanctionAmount_);
      }
      if (!getScanctiondtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, scanctiondt_);
      }
      if (!getInstallmentAmtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, installmentAmt_);
      }
      if (noofinstallments_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, noofinstallments_);
      }
      if (!getOutstandingBalBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, outstandingBal_);
      }
      if (!getExpirydateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, expirydate_);
      }
      if (!getOverdueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, overdue_);
      }
      if (pendingInstlmnts_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, pendingInstlmnts_);
      }
      if (!getTxndateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, txndate_);
      }
      if (!getTxnStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, txnStatus_);
      }
      if (!getReserve1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, reserve1_);
      }
      if (!getReserve2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, reserve2_);
      }
      if (!getReserve3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, reserve3_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof   LoandetailsProto.LoanDetailsProto)) {
        return super.equals(obj);
      }
        LoandetailsProto.LoanDetailsProto other = (  LoandetailsProto.LoanDetailsProto) obj;

      boolean result = true;
      result = result && (getAgentid()
          == other.getAgentid());
      result = result && (getMicroatmid()
          == other.getMicroatmid());
      result = result && (getBranchid()
          == other.getBranchid());
      result = result && getBranchcode()
          .equals(other.getBranchcode());
      result = result && getAccountNo()
          .equals(other.getAccountNo());
      result = result && getCustName()
          .equals(other.getCustName());
      result = result && getScanctionAmount()
          .equals(other.getScanctionAmount());
      result = result && getScanctiondt()
          .equals(other.getScanctiondt());
      result = result && getInstallmentAmt()
          .equals(other.getInstallmentAmt());
      result = result && (getNoofinstallments()
          == other.getNoofinstallments());
      result = result && getOutstandingBal()
          .equals(other.getOutstandingBal());
      result = result && getExpirydate()
          .equals(other.getExpirydate());
      result = result && getOverdue()
          .equals(other.getOverdue());
      result = result && (getPendingInstlmnts()
          == other.getPendingInstlmnts());
      result = result && getTxndate()
          .equals(other.getTxndate());
      result = result && getTxnStatus()
          .equals(other.getTxnStatus());
      result = result && getReserve1()
          .equals(other.getReserve1());
      result = result && getReserve2()
          .equals(other.getReserve2());
      result = result && getReserve3()
          .equals(other.getReserve3());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGENTID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentid();
      hash = (37 * hash) + MICROATMID_FIELD_NUMBER;
      hash = (53 * hash) + getMicroatmid();
      hash = (37 * hash) + BRANCHID_FIELD_NUMBER;
      hash = (53 * hash) + getBranchid();
      hash = (37 * hash) + BRANCHCODE_FIELD_NUMBER;
      hash = (53 * hash) + getBranchcode().hashCode();
      hash = (37 * hash) + ACCOUNTNO_FIELD_NUMBER;
      hash = (53 * hash) + getAccountNo().hashCode();
      hash = (37 * hash) + CUSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCustName().hashCode();
      hash = (37 * hash) + SCANCTIONAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getScanctionAmount().hashCode();
      hash = (37 * hash) + SCANCTIONDT_FIELD_NUMBER;
      hash = (53 * hash) + getScanctiondt().hashCode();
      hash = (37 * hash) + INSTALLMENTAMT_FIELD_NUMBER;
      hash = (53 * hash) + getInstallmentAmt().hashCode();
      hash = (37 * hash) + NOOFINSTALLMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getNoofinstallments();
      hash = (37 * hash) + OUTSTANDINGBAL_FIELD_NUMBER;
      hash = (53 * hash) + getOutstandingBal().hashCode();
      hash = (37 * hash) + EXPIRYDATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpirydate().hashCode();
      hash = (37 * hash) + OVERDUE_FIELD_NUMBER;
      hash = (53 * hash) + getOverdue().hashCode();
      hash = (37 * hash) + PENDINGINSTLMNTS_FIELD_NUMBER;
      hash = (53 * hash) + getPendingInstlmnts();
      hash = (37 * hash) + TXNDATE_FIELD_NUMBER;
      hash = (53 * hash) + getTxndate().hashCode();
      hash = (37 * hash) + TXNSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getTxnStatus().hashCode();
      hash = (37 * hash) + RESERVE1_FIELD_NUMBER;
      hash = (53 * hash) + getReserve1().hashCode();
      hash = (37 * hash) + RESERVE2_FIELD_NUMBER;
      hash = (53 * hash) + getReserve2().hashCode();
      hash = (37 * hash) + RESERVE3_FIELD_NUMBER;
      hash = (53 * hash) + getReserve3().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static   LoandetailsProto.LoanDetailsProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static   LoandetailsProto.LoanDetailsProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static   LoandetailsProto.LoanDetailsProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static   LoandetailsProto.LoanDetailsProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(  LoandetailsProto.LoanDetailsProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code   LoanDetailsProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:  LoanDetailsProto)
          LoandetailsProto.LoanDetailsProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return   LoandetailsProto.internal_static_VCBL_Transaction_LoanDetailsProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return   LoandetailsProto.internal_static_VCBL_Transaction_LoanDetailsProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                  LoandetailsProto.LoanDetailsProto.class,   LoandetailsProto.LoanDetailsProto.Builder.class);
      }

      // Construct using   LoandetailsProto.LoanDetailsProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        agentid_ = 0;

        microatmid_ = 0;

        branchid_ = 0;

        branchcode_ = "";

        accountNo_ = "";

        custName_ = "";

        scanctionAmount_ = "";

        scanctiondt_ = "";

        installmentAmt_ = "";

        noofinstallments_ = 0;

        outstandingBal_ = "";

        expirydate_ = "";

        overdue_ = "";

        pendingInstlmnts_ = 0;

        txndate_ = "";

        txnStatus_ = "";

        reserve1_ = "";

        reserve2_ = "";

        reserve3_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return   LoandetailsProto.internal_static_VCBL_Transaction_LoanDetailsProto_descriptor;
      }

      public   LoandetailsProto.LoanDetailsProto getDefaultInstanceForType() {
        return   LoandetailsProto.LoanDetailsProto.getDefaultInstance();
      }

      public   LoandetailsProto.LoanDetailsProto build() {
          LoandetailsProto.LoanDetailsProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LoandetailsProto.LoanDetailsProto buildPartial() {
        LoandetailsProto.LoanDetailsProto result = new   LoandetailsProto.LoanDetailsProto(this);
        result.agentid_ = agentid_;
        result.microatmid_ = microatmid_;
        result.branchid_ = branchid_;
        result.branchcode_ = branchcode_;
        result.accountNo_ = accountNo_;
        result.custName_ = custName_;
        result.scanctionAmount_ = scanctionAmount_;
        result.scanctiondt_ = scanctiondt_;
        result.installmentAmt_ = installmentAmt_;
        result.noofinstallments_ = noofinstallments_;
        result.outstandingBal_ = outstandingBal_;
        result.expirydate_ = expirydate_;
        result.overdue_ = overdue_;
        result.pendingInstlmnts_ = pendingInstlmnts_;
        result.txndate_ = txndate_;
        result.txnStatus_ = txnStatus_;
        result.reserve1_ = reserve1_;
        result.reserve2_ = reserve2_;
        result.reserve3_ = reserve3_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof   LoandetailsProto.LoanDetailsProto) {
          return mergeFrom((  LoandetailsProto.LoanDetailsProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(  LoandetailsProto.LoanDetailsProto other) {
        if (other ==   LoandetailsProto.LoanDetailsProto.getDefaultInstance()) return this;
        if (other.getAgentid() != 0) {
          setAgentid(other.getAgentid());
        }
        if (other.getMicroatmid() != 0) {
          setMicroatmid(other.getMicroatmid());
        }
        if (other.getBranchid() != 0) {
          setBranchid(other.getBranchid());
        }
        if (!other.getBranchcode().isEmpty()) {
          branchcode_ = other.branchcode_;
          onChanged();
        }
        if (!other.getAccountNo().isEmpty()) {
          accountNo_ = other.accountNo_;
          onChanged();
        }
        if (!other.getCustName().isEmpty()) {
          custName_ = other.custName_;
          onChanged();
        }
        if (!other.getScanctionAmount().isEmpty()) {
          scanctionAmount_ = other.scanctionAmount_;
          onChanged();
        }
        if (!other.getScanctiondt().isEmpty()) {
          scanctiondt_ = other.scanctiondt_;
          onChanged();
        }
        if (!other.getInstallmentAmt().isEmpty()) {
          installmentAmt_ = other.installmentAmt_;
          onChanged();
        }
        if (other.getNoofinstallments() != 0) {
          setNoofinstallments(other.getNoofinstallments());
        }
        if (!other.getOutstandingBal().isEmpty()) {
          outstandingBal_ = other.outstandingBal_;
          onChanged();
        }
        if (!other.getExpirydate().isEmpty()) {
          expirydate_ = other.expirydate_;
          onChanged();
        }
        if (!other.getOverdue().isEmpty()) {
          overdue_ = other.overdue_;
          onChanged();
        }
        if (other.getPendingInstlmnts() != 0) {
          setPendingInstlmnts(other.getPendingInstlmnts());
        }
        if (!other.getTxndate().isEmpty()) {
          txndate_ = other.txndate_;
          onChanged();
        }
        if (!other.getTxnStatus().isEmpty()) {
          txnStatus_ = other.txnStatus_;
          onChanged();
        }
        if (!other.getReserve1().isEmpty()) {
          reserve1_ = other.reserve1_;
          onChanged();
        }
        if (!other.getReserve2().isEmpty()) {
          reserve2_ = other.reserve2_;
          onChanged();
        }
        if (!other.getReserve3().isEmpty()) {
          reserve3_ = other.reserve3_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
          LoandetailsProto.LoanDetailsProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (  LoandetailsProto.LoanDetailsProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int agentid_ ;
      /**
       * <code>int32 agentid = 1;</code>
       */
      public int getAgentid() {
        return agentid_;
      }
      /**
       * <code>int32 agentid = 1;</code>
       */
      public Builder setAgentid(int value) {
        
        agentid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 agentid = 1;</code>
       */
      public Builder clearAgentid() {
        
        agentid_ = 0;
        onChanged();
        return this;
      }

      private int microatmid_ ;
      /**
       * <code>int32 microatmid = 2;</code>
       */
      public int getMicroatmid() {
        return microatmid_;
      }
      /**
       * <code>int32 microatmid = 2;</code>
       */
      public Builder setMicroatmid(int value) {
        
        microatmid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 microatmid = 2;</code>
       */
      public Builder clearMicroatmid() {
        
        microatmid_ = 0;
        onChanged();
        return this;
      }

      private int branchid_ ;
      /**
       * <code>int32 branchid = 3;</code>
       */
      public int getBranchid() {
        return branchid_;
      }
      /**
       * <code>int32 branchid = 3;</code>
       */
      public Builder setBranchid(int value) {
        
        branchid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 branchid = 3;</code>
       */
      public Builder clearBranchid() {
        
        branchid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object branchcode_ = "";
      /**
       * <code>string branchcode = 4;</code>
       */
      public java.lang.String getBranchcode() {
        java.lang.Object ref = branchcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          branchcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string branchcode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBranchcodeBytes() {
        java.lang.Object ref = branchcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          branchcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string branchcode = 4;</code>
       */
      public Builder setBranchcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        branchcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string branchcode = 4;</code>
       */
      public Builder clearBranchcode() {
        
        branchcode_ = getDefaultInstance().getBranchcode();
        onChanged();
        return this;
      }
      /**
       * <code>string branchcode = 4;</code>
       */
      public Builder setBranchcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        branchcode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accountNo_ = "";
      /**
       * <code>string AccountNo = 5;</code>
       */
      public java.lang.String getAccountNo() {
        java.lang.Object ref = accountNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string AccountNo = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNoBytes() {
        java.lang.Object ref = accountNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string AccountNo = 5;</code>
       */
      public Builder setAccountNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string AccountNo = 5;</code>
       */
      public Builder clearAccountNo() {
        
        accountNo_ = getDefaultInstance().getAccountNo();
        onChanged();
        return this;
      }
      /**
       * <code>string AccountNo = 5;</code>
       */
      public Builder setAccountNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object custName_ = "";
      /**
       * <code>string CustName = 6;</code>
       */
      public java.lang.String getCustName() {
        java.lang.Object ref = custName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          custName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string CustName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCustNameBytes() {
        java.lang.Object ref = custName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          custName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string CustName = 6;</code>
       */
      public Builder setCustName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        custName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string CustName = 6;</code>
       */
      public Builder clearCustName() {
        
        custName_ = getDefaultInstance().getCustName();
        onChanged();
        return this;
      }
      /**
       * <code>string CustName = 6;</code>
       */
      public Builder setCustNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        custName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scanctionAmount_ = "";
      /**
       * <code>string ScanctionAmount = 7;</code>
       */
      public java.lang.String getScanctionAmount() {
        java.lang.Object ref = scanctionAmount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scanctionAmount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ScanctionAmount = 7;</code>
       */
      public com.google.protobuf.ByteString
          getScanctionAmountBytes() {
        java.lang.Object ref = scanctionAmount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scanctionAmount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ScanctionAmount = 7;</code>
       */
      public Builder setScanctionAmount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scanctionAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ScanctionAmount = 7;</code>
       */
      public Builder clearScanctionAmount() {
        
        scanctionAmount_ = getDefaultInstance().getScanctionAmount();
        onChanged();
        return this;
      }
      /**
       * <code>string ScanctionAmount = 7;</code>
       */
      public Builder setScanctionAmountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        scanctionAmount_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scanctiondt_ = "";
      /**
       * <code>string Scanctiondt = 8;</code>
       */
      public java.lang.String getScanctiondt() {
        java.lang.Object ref = scanctiondt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scanctiondt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Scanctiondt = 8;</code>
       */
      public com.google.protobuf.ByteString
          getScanctiondtBytes() {
        java.lang.Object ref = scanctiondt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scanctiondt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Scanctiondt = 8;</code>
       */
      public Builder setScanctiondt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scanctiondt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Scanctiondt = 8;</code>
       */
      public Builder clearScanctiondt() {
        
        scanctiondt_ = getDefaultInstance().getScanctiondt();
        onChanged();
        return this;
      }
      /**
       * <code>string Scanctiondt = 8;</code>
       */
      public Builder setScanctiondtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        scanctiondt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object installmentAmt_ = "";
      /**
       * <code>string InstallmentAmt = 9;</code>
       */
      public java.lang.String getInstallmentAmt() {
        java.lang.Object ref = installmentAmt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          installmentAmt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string InstallmentAmt = 9;</code>
       */
      public com.google.protobuf.ByteString
          getInstallmentAmtBytes() {
        java.lang.Object ref = installmentAmt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          installmentAmt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string InstallmentAmt = 9;</code>
       */
      public Builder setInstallmentAmt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        installmentAmt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string InstallmentAmt = 9;</code>
       */
      public Builder clearInstallmentAmt() {
        
        installmentAmt_ = getDefaultInstance().getInstallmentAmt();
        onChanged();
        return this;
      }
      /**
       * <code>string InstallmentAmt = 9;</code>
       */
      public Builder setInstallmentAmtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        installmentAmt_ = value;
        onChanged();
        return this;
      }

      private int noofinstallments_ ;
      /**
       * <code>int32 Noofinstallments = 10;</code>
       */
      public int getNoofinstallments() {
        return noofinstallments_;
      }
      /**
       * <code>int32 Noofinstallments = 10;</code>
       */
      public Builder setNoofinstallments(int value) {
        
        noofinstallments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Noofinstallments = 10;</code>
       */
      public Builder clearNoofinstallments() {
        
        noofinstallments_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object outstandingBal_ = "";
      /**
       * <code>string OutstandingBal = 11;</code>
       */
      public java.lang.String getOutstandingBal() {
        java.lang.Object ref = outstandingBal_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          outstandingBal_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string OutstandingBal = 11;</code>
       */
      public com.google.protobuf.ByteString
          getOutstandingBalBytes() {
        java.lang.Object ref = outstandingBal_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outstandingBal_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string OutstandingBal = 11;</code>
       */
      public Builder setOutstandingBal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        outstandingBal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string OutstandingBal = 11;</code>
       */
      public Builder clearOutstandingBal() {
        
        outstandingBal_ = getDefaultInstance().getOutstandingBal();
        onChanged();
        return this;
      }
      /**
       * <code>string OutstandingBal = 11;</code>
       */
      public Builder setOutstandingBalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        outstandingBal_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object expirydate_ = "";
      /**
       * <code>string Expirydate = 12;</code>
       */
      public java.lang.String getExpirydate() {
        java.lang.Object ref = expirydate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expirydate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Expirydate = 12;</code>
       */
      public com.google.protobuf.ByteString
          getExpirydateBytes() {
        java.lang.Object ref = expirydate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expirydate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Expirydate = 12;</code>
       */
      public Builder setExpirydate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expirydate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Expirydate = 12;</code>
       */
      public Builder clearExpirydate() {
        
        expirydate_ = getDefaultInstance().getExpirydate();
        onChanged();
        return this;
      }
      /**
       * <code>string Expirydate = 12;</code>
       */
      public Builder setExpirydateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expirydate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object overdue_ = "";
      /**
       * <code>string Overdue = 13;</code>
       */
      public java.lang.String getOverdue() {
        java.lang.Object ref = overdue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          overdue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Overdue = 13;</code>
       */
      public com.google.protobuf.ByteString
          getOverdueBytes() {
        java.lang.Object ref = overdue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          overdue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Overdue = 13;</code>
       */
      public Builder setOverdue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        overdue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Overdue = 13;</code>
       */
      public Builder clearOverdue() {
        
        overdue_ = getDefaultInstance().getOverdue();
        onChanged();
        return this;
      }
      /**
       * <code>string Overdue = 13;</code>
       */
      public Builder setOverdueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        overdue_ = value;
        onChanged();
        return this;
      }

      private int pendingInstlmnts_ ;
      /**
       * <code>int32 pendingInstlmnts = 14;</code>
       */
      public int getPendingInstlmnts() {
        return pendingInstlmnts_;
      }
      /**
       * <code>int32 pendingInstlmnts = 14;</code>
       */
      public Builder setPendingInstlmnts(int value) {
        
        pendingInstlmnts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pendingInstlmnts = 14;</code>
       */
      public Builder clearPendingInstlmnts() {
        
        pendingInstlmnts_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object txndate_ = "";
      /**
       * <code>string txndate = 15;</code>
       */
      public java.lang.String getTxndate() {
        java.lang.Object ref = txndate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txndate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txndate = 15;</code>
       */
      public com.google.protobuf.ByteString
          getTxndateBytes() {
        java.lang.Object ref = txndate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txndate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txndate = 15;</code>
       */
      public Builder setTxndate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txndate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txndate = 15;</code>
       */
      public Builder clearTxndate() {
        
        txndate_ = getDefaultInstance().getTxndate();
        onChanged();
        return this;
      }
      /**
       * <code>string txndate = 15;</code>
       */
      public Builder setTxndateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txndate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object txnStatus_ = "";
      /**
       * <code>string txnStatus = 16;</code>
       */
      public java.lang.String getTxnStatus() {
        java.lang.Object ref = txnStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txnStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txnStatus = 16;</code>
       */
      public com.google.protobuf.ByteString
          getTxnStatusBytes() {
        java.lang.Object ref = txnStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txnStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txnStatus = 16;</code>
       */
      public Builder setTxnStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txnStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txnStatus = 16;</code>
       */
      public Builder clearTxnStatus() {
        
        txnStatus_ = getDefaultInstance().getTxnStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string txnStatus = 16;</code>
       */
      public Builder setTxnStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txnStatus_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reserve1_ = "";
      /**
       * <code>string reserve1 = 17;</code>
       */
      public java.lang.String getReserve1() {
        java.lang.Object ref = reserve1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reserve1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reserve1 = 17;</code>
       */
      public com.google.protobuf.ByteString
          getReserve1Bytes() {
        java.lang.Object ref = reserve1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reserve1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reserve1 = 17;</code>
       */
      public Builder setReserve1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reserve1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reserve1 = 17;</code>
       */
      public Builder clearReserve1() {
        
        reserve1_ = getDefaultInstance().getReserve1();
        onChanged();
        return this;
      }
      /**
       * <code>string reserve1 = 17;</code>
       */
      public Builder setReserve1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reserve1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reserve2_ = "";
      /**
       * <code>string reserve2 = 18;</code>
       */
      public java.lang.String getReserve2() {
        java.lang.Object ref = reserve2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reserve2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reserve2 = 18;</code>
       */
      public com.google.protobuf.ByteString
          getReserve2Bytes() {
        java.lang.Object ref = reserve2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reserve2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reserve2 = 18;</code>
       */
      public Builder setReserve2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reserve2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reserve2 = 18;</code>
       */
      public Builder clearReserve2() {
        
        reserve2_ = getDefaultInstance().getReserve2();
        onChanged();
        return this;
      }
      /**
       * <code>string reserve2 = 18;</code>
       */
      public Builder setReserve2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reserve2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reserve3_ = "";
      /**
       * <code>string reserve3 = 19;</code>
       */
      public java.lang.String getReserve3() {
        java.lang.Object ref = reserve3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reserve3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reserve3 = 19;</code>
       */
      public com.google.protobuf.ByteString
          getReserve3Bytes() {
        java.lang.Object ref = reserve3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reserve3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reserve3 = 19;</code>
       */
      public Builder setReserve3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reserve3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reserve3 = 19;</code>
       */
      public Builder clearReserve3() {
        
        reserve3_ = getDefaultInstance().getReserve3();
        onChanged();
        return this;
      }
      /**
       * <code>string reserve3 = 19;</code>
       */
      public Builder setReserve3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reserve3_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:  LoanDetailsProto)
    }

    // @@protoc_insertion_point(class_scope:  LoanDetailsProto)
    private static final   LoandetailsProto.LoanDetailsProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new   LoandetailsProto.LoanDetailsProto();
    }

    public static   LoandetailsProto.LoanDetailsProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoanDetailsProto>
        PARSER = new com.google.protobuf.AbstractParser<LoanDetailsProto>() {
      public LoanDetailsProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoanDetailsProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoanDetailsProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoanDetailsProto> getParserForType() {
      return PARSER;
    }

    public   LoandetailsProto.LoanDetailsProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VCBL_Transaction_LoanDetailsProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VCBL_Transaction_LoanDetailsProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026LoandetailsProto.proto\022\020VCBL.Transacti" +
      "on\"\223\003\n\020LoanDetailsProto\022\017\n\007agentid\030\001 \001(\005" +
      "\022\022\n\nmicroatmid\030\002 \001(\005\022\020\n\010branchid\030\003 \001(\005\022\022" +
      "\n\nbranchcode\030\004 \001(\t\022\021\n\tAccountNo\030\005 \001(\t\022\020\n" +
      "\010CustName\030\006 \001(\t\022\027\n\017ScanctionAmount\030\007 \001(\t" +
      "\022\023\n\013Scanctiondt\030\010 \001(\t\022\026\n\016InstallmentAmt\030" +
      "\t \001(\t\022\030\n\020Noofinstallments\030\n \001(\005\022\026\n\016Outst" +
      "andingBal\030\013 \001(\t\022\022\n\nExpirydate\030\014 \001(\t\022\017\n\007O" +
      "verdue\030\r \001(\t\022\030\n\020pendingInstlmnts\030\016 \001(\005\022\017" +
      "\n\007txndate\030\017 \001(\t\022\021\n\ttxnStatus\030\020 \001(\t\022\020\n\010re",
      "serve1\030\021 \001(\t\022\020\n\010reserve2\030\022 \001(\t\022\020\n\010reserv" +
      "e3\030\023 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VCBL_Transaction_LoanDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VCBL_Transaction_LoanDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VCBL_Transaction_LoanDetailsProto_descriptor,
        new java.lang.String[] { "Agentid", "Microatmid", "Branchid", "Branchcode", "AccountNo", "CustName", "ScanctionAmount", "Scanctiondt", "InstallmentAmt", "Noofinstallments", "OutstandingBal", "Expirydate", "Overdue", "PendingInstlmnts", "Txndate", "TxnStatus", "Reserve1", "Reserve2", "Reserve3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
