// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TxnMessage.proto

package com.vcbl.tabbanking.protobuff;

public final class TxnMessage {
  private TxnMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TxnRequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TxnRequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 microatmid = 1;</code>
     */
    int getMicroatmid();

    /**
     * <code>string timestamp = 2;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>string appVersion = 3;</code>
     */
    java.lang.String getAppVersion();
    /**
     * <code>string appVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();

    /**
     * <code>.TransactionProto transactionProto = 4;</code>
     */
    boolean hasTransactionProto();
    /**
     * <code>.TransactionProto transactionProto = 4;</code>
     */
    Transaction.TransactionProto getTransactionProto();
    /**
     * <code>.TransactionProto transactionProto = 4;</code>
     */
    Transaction.TransactionProtoOrBuilder getTransactionProtoOrBuilder();
  }
  /**
   * Protobuf type {@code TxnRequestProto}
   */
  public  static final class TxnRequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TxnRequestProto)
      TxnRequestProtoOrBuilder {
    // Use TxnRequestProto.newBuilder() to construct.
    private TxnRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxnRequestProto() {
      microatmid_ = 0;
      timestamp_ = "";
      appVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TxnRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              microatmid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appVersion_ = s;
              break;
            }
            case 34: {
              Transaction.TransactionProto.Builder subBuilder = null;
              if (transactionProto_ != null) {
                subBuilder = transactionProto_.toBuilder();
              }
              transactionProto_ = input.readMessage(Transaction.TransactionProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactionProto_);
                transactionProto_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TxnMessage.internal_static_VCBL_Transaction_TxnRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TxnMessage.internal_static_VCBL_Transaction_TxnRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxnMessage.TxnRequestProto.class, TxnMessage.TxnRequestProto.Builder.class);
    }

    public static final int MICROATMID_FIELD_NUMBER = 1;
    private int microatmid_;
    /**
     * <code>int32 microatmid = 1;</code>
     */
    public int getMicroatmid() {
      return microatmid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>string timestamp = 2;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPVERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object appVersion_;
    /**
     * <code>string appVersion = 3;</code>
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string appVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTIONPROTO_FIELD_NUMBER = 4;
    private Transaction.TransactionProto transactionProto_;
    /**
     * <code>.TransactionProto transactionProto = 4;</code>
     */
    public boolean hasTransactionProto() {
      return transactionProto_ != null;
    }
    /**
     * <code>.TransactionProto transactionProto = 4;</code>
     */
    public Transaction.TransactionProto getTransactionProto() {
      return transactionProto_ == null ? Transaction.TransactionProto.getDefaultInstance() : transactionProto_;
    }
    /**
     * <code>.TransactionProto transactionProto = 4;</code>
     */
    public Transaction.TransactionProtoOrBuilder getTransactionProtoOrBuilder() {
      return getTransactionProto();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (microatmid_ != 0) {
        output.writeInt32(1, microatmid_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timestamp_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appVersion_);
      }
      if (transactionProto_ != null) {
        output.writeMessage(4, getTransactionProto());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (microatmid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, microatmid_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timestamp_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appVersion_);
      }
      if (transactionProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTransactionProto());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxnMessage.TxnRequestProto)) {
        return super.equals(obj);
      }
      TxnMessage.TxnRequestProto other = (TxnMessage.TxnRequestProto) obj;

      boolean result = true;
      result = result && (getMicroatmid()
          == other.getMicroatmid());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && getAppVersion()
          .equals(other.getAppVersion());
      result = result && (hasTransactionProto() == other.hasTransactionProto());
      if (hasTransactionProto()) {
        result = result && getTransactionProto()
            .equals(other.getTransactionProto());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MICROATMID_FIELD_NUMBER;
      hash = (53 * hash) + getMicroatmid();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersion().hashCode();
      if (hasTransactionProto()) {
        hash = (37 * hash) + TRANSACTIONPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionProto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxnMessage.TxnRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage.TxnRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage.TxnRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage.TxnRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage.TxnRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnMessage.TxnRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnMessage.TxnRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxnMessage.TxnRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnMessage.TxnRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnMessage.TxnRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxnMessage.TxnRequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TxnRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TxnRequestProto)
        TxnMessage.TxnRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TxnMessage.internal_static_VCBL_Transaction_TxnRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TxnMessage.internal_static_VCBL_Transaction_TxnRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxnMessage.TxnRequestProto.class, TxnMessage.TxnRequestProto.Builder.class);
      }

      // Construct using TxnMessage.TxnRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        microatmid_ = 0;

        timestamp_ = "";

        appVersion_ = "";

        if (transactionProtoBuilder_ == null) {
          transactionProto_ = null;
        } else {
          transactionProto_ = null;
          transactionProtoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TxnMessage.internal_static_VCBL_Transaction_TxnRequestProto_descriptor;
      }

      public TxnMessage.TxnRequestProto getDefaultInstanceForType() {
        return TxnMessage.TxnRequestProto.getDefaultInstance();
      }

      public TxnMessage.TxnRequestProto build() {
        TxnMessage.TxnRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxnMessage.TxnRequestProto buildPartial() {
        TxnMessage.TxnRequestProto result = new TxnMessage.TxnRequestProto(this);
        result.microatmid_ = microatmid_;
        result.timestamp_ = timestamp_;
        result.appVersion_ = appVersion_;
        if (transactionProtoBuilder_ == null) {
          result.transactionProto_ = transactionProto_;
        } else {
          result.transactionProto_ = transactionProtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxnMessage.TxnRequestProto) {
          return mergeFrom((TxnMessage.TxnRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxnMessage.TxnRequestProto other) {
        if (other == TxnMessage.TxnRequestProto.getDefaultInstance()) return this;
        if (other.getMicroatmid() != 0) {
          setMicroatmid(other.getMicroatmid());
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getAppVersion().isEmpty()) {
          appVersion_ = other.appVersion_;
          onChanged();
        }
        if (other.hasTransactionProto()) {
          mergeTransactionProto(other.getTransactionProto());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxnMessage.TxnRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxnMessage.TxnRequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int microatmid_ ;
      /**
       * <code>int32 microatmid = 1;</code>
       */
      public int getMicroatmid() {
        return microatmid_;
      }
      /**
       * <code>int32 microatmid = 1;</code>
       */
      public Builder setMicroatmid(int value) {
        
        microatmid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 microatmid = 1;</code>
       */
      public Builder clearMicroatmid() {
        
        microatmid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 2;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appVersion_ = "";
      /**
       * <code>string appVersion = 3;</code>
       */
      public java.lang.String getAppVersion() {
        java.lang.Object ref = appVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        java.lang.Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public Builder setAppVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public Builder clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value;
        onChanged();
        return this;
      }

      private Transaction.TransactionProto transactionProto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Transaction.TransactionProto, Transaction.TransactionProto.Builder, Transaction.TransactionProtoOrBuilder> transactionProtoBuilder_;
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public boolean hasTransactionProto() {
        return transactionProtoBuilder_ != null || transactionProto_ != null;
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Transaction.TransactionProto getTransactionProto() {
        if (transactionProtoBuilder_ == null) {
          return transactionProto_ == null ? Transaction.TransactionProto.getDefaultInstance() : transactionProto_;
        } else {
          return transactionProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Builder setTransactionProto(Transaction.TransactionProto value) {
        if (transactionProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactionProto_ = value;
          onChanged();
        } else {
          transactionProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Builder setTransactionProto(
          Transaction.TransactionProto.Builder builderForValue) {
        if (transactionProtoBuilder_ == null) {
          transactionProto_ = builderForValue.build();
          onChanged();
        } else {
          transactionProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Builder mergeTransactionProto(Transaction.TransactionProto value) {
        if (transactionProtoBuilder_ == null) {
          if (transactionProto_ != null) {
            transactionProto_ =
              Transaction.TransactionProto.newBuilder(transactionProto_).mergeFrom(value).buildPartial();
          } else {
            transactionProto_ = value;
          }
          onChanged();
        } else {
          transactionProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Builder clearTransactionProto() {
        if (transactionProtoBuilder_ == null) {
          transactionProto_ = null;
          onChanged();
        } else {
          transactionProto_ = null;
          transactionProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Transaction.TransactionProto.Builder getTransactionProtoBuilder() {
        
        onChanged();
        return getTransactionProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      public Transaction.TransactionProtoOrBuilder getTransactionProtoOrBuilder() {
        if (transactionProtoBuilder_ != null) {
          return transactionProtoBuilder_.getMessageOrBuilder();
        } else {
          return transactionProto_ == null ?
              Transaction.TransactionProto.getDefaultInstance() : transactionProto_;
        }
      }
      /**
       * <code>.TransactionProto transactionProto = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Transaction.TransactionProto, Transaction.TransactionProto.Builder, Transaction.TransactionProtoOrBuilder> 
          getTransactionProtoFieldBuilder() {
        if (transactionProtoBuilder_ == null) {
          transactionProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Transaction.TransactionProto, Transaction.TransactionProto.Builder, Transaction.TransactionProtoOrBuilder>(
                  getTransactionProto(),
                  getParentForChildren(),
                  isClean());
          transactionProto_ = null;
        }
        return transactionProtoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TxnRequestProto)
    }

    // @@protoc_insertion_point(class_scope:TxnRequestProto)
    private static final TxnMessage.TxnRequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxnMessage.TxnRequestProto();
    }

    public static TxnMessage.TxnRequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxnRequestProto>
        PARSER = new com.google.protobuf.AbstractParser<TxnRequestProto>() {
      public TxnRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TxnRequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxnRequestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxnRequestProto> getParserForType() {
      return PARSER;
    }

    public TxnMessage.TxnRequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxnResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TxnResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 microatmid = 1;</code>
     */
    int getMicroatmid();

    /**
     * <code>string timestamp = 2;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>string appVersion = 3;</code>
     */
    java.lang.String getAppVersion();
    /**
     * <code>string appVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();

    /**
     * <code>.Status status = 4;</code>
     */
    int getStatusValue();
    /**
     * <code>.Status status = 4;</code>
     */
    Masters.Status getStatus();

    /**
     * <code>string statusDescription = 5;</code>
     */
    java.lang.String getStatusDescription();
    /**
     * <code>string statusDescription = 5;</code>
     */
    com.google.protobuf.ByteString
        getStatusDescriptionBytes();

    /**
     * <code>.TransactionProto transactionProto = 6;</code>
     */
    boolean hasTransactionProto();
    /**
     * <code>.TransactionProto transactionProto = 6;</code>
     */
    Transaction.TransactionProto getTransactionProto();
    /**
     * <code>.TransactionProto transactionProto = 6;</code>
     */
    Transaction.TransactionProtoOrBuilder getTransactionProtoOrBuilder();

    /**
     * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
     */
    boolean hasLoanDetailsProto();
    /**
     * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
     */
    Loandetails.LoanDetailsProto getLoanDetailsProto();
    /**
     * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
     */
    Loandetails.LoanDetailsProtoOrBuilder getLoanDetailsProtoOrBuilder();
  }
  /**
   * Protobuf type {@code TxnResponseProto}
   */
  public  static final class TxnResponseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TxnResponseProto)
      TxnResponseProtoOrBuilder {
    // Use TxnResponseProto.newBuilder() to construct.
    private TxnResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxnResponseProto() {
      microatmid_ = 0;
      timestamp_ = "";
      appVersion_ = "";
      status_ = 0;
      statusDescription_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TxnResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              microatmid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appVersion_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              statusDescription_ = s;
              break;
            }
            case 50: {
              Transaction.TransactionProto.Builder subBuilder = null;
              if (transactionProto_ != null) {
                subBuilder = transactionProto_.toBuilder();
              }
              transactionProto_ = input.readMessage(Transaction.TransactionProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactionProto_);
                transactionProto_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              Loandetails.LoanDetailsProto.Builder subBuilder = null;
              if (loanDetailsProto_ != null) {
                subBuilder = loanDetailsProto_.toBuilder();
              }
              loanDetailsProto_ = input.readMessage(Loandetails.LoanDetailsProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loanDetailsProto_);
                loanDetailsProto_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TxnMessage.internal_static_VCBL_Transaction_TxnResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TxnMessage.internal_static_VCBL_Transaction_TxnResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxnMessage.TxnResponseProto.class, TxnMessage.TxnResponseProto.Builder.class);
    }

    public static final int MICROATMID_FIELD_NUMBER = 1;
    private int microatmid_;
    /**
     * <code>int32 microatmid = 1;</code>
     */
    public int getMicroatmid() {
      return microatmid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>string timestamp = 2;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPVERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object appVersion_;
    /**
     * <code>string appVersion = 3;</code>
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string appVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>.Status status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 4;</code>
     */
    public Masters.Status getStatus() {
      Masters.Status result = Masters.Status.valueOf(status_);
      return result == null ? Masters.Status.UNRECOGNIZED : result;
    }

    public static final int STATUSDESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object statusDescription_;
    /**
     * <code>string statusDescription = 5;</code>
     */
    public java.lang.String getStatusDescription() {
      java.lang.Object ref = statusDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string statusDescription = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStatusDescriptionBytes() {
      java.lang.Object ref = statusDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTIONPROTO_FIELD_NUMBER = 6;
    private Transaction.TransactionProto transactionProto_;
    /**
     * <code>.TransactionProto transactionProto = 6;</code>
     */
    public boolean hasTransactionProto() {
      return transactionProto_ != null;
    }
    /**
     * <code>.TransactionProto transactionProto = 6;</code>
     */
    public Transaction.TransactionProto getTransactionProto() {
      return transactionProto_ == null ? Transaction.TransactionProto.getDefaultInstance() : transactionProto_;
    }
    /**
     * <code>.TransactionProto transactionProto = 6;</code>
     */
    public Transaction.TransactionProtoOrBuilder getTransactionProtoOrBuilder() {
      return getTransactionProto();
    }

    public static final int LOANDETAILSPROTO_FIELD_NUMBER = 7;
    private Loandetails.LoanDetailsProto loanDetailsProto_;
    /**
     * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
     */
    public boolean hasLoanDetailsProto() {
      return loanDetailsProto_ != null;
    }
    /**
     * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
     */
    public Loandetails.LoanDetailsProto getLoanDetailsProto() {
      return loanDetailsProto_ == null ? Loandetails.LoanDetailsProto.getDefaultInstance() : loanDetailsProto_;
    }
    /**
     * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
     */
    public Loandetails.LoanDetailsProtoOrBuilder getLoanDetailsProtoOrBuilder() {
      return getLoanDetailsProto();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (microatmid_ != 0) {
        output.writeInt32(1, microatmid_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timestamp_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appVersion_);
      }
      if (status_ != Masters.Status.SUCCESS.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (!getStatusDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, statusDescription_);
      }
      if (transactionProto_ != null) {
        output.writeMessage(6, getTransactionProto());
      }
      if (loanDetailsProto_ != null) {
        output.writeMessage(7, getLoanDetailsProto());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (microatmid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, microatmid_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timestamp_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appVersion_);
      }
      if (status_ != Masters.Status.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (!getStatusDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, statusDescription_);
      }
      if (transactionProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getTransactionProto());
      }
      if (loanDetailsProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getLoanDetailsProto());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxnMessage.TxnResponseProto)) {
        return super.equals(obj);
      }
      TxnMessage.TxnResponseProto other = (TxnMessage.TxnResponseProto) obj;

      boolean result = true;
      result = result && (getMicroatmid()
          == other.getMicroatmid());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && getAppVersion()
          .equals(other.getAppVersion());
      result = result && status_ == other.status_;
      result = result && getStatusDescription()
          .equals(other.getStatusDescription());
      result = result && (hasTransactionProto() == other.hasTransactionProto());
      if (hasTransactionProto()) {
        result = result && getTransactionProto()
            .equals(other.getTransactionProto());
      }
      result = result && (hasLoanDetailsProto() == other.hasLoanDetailsProto());
      if (hasLoanDetailsProto()) {
        result = result && getLoanDetailsProto()
            .equals(other.getLoanDetailsProto());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MICROATMID_FIELD_NUMBER;
      hash = (53 * hash) + getMicroatmid();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersion().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + STATUSDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getStatusDescription().hashCode();
      if (hasTransactionProto()) {
        hash = (37 * hash) + TRANSACTIONPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionProto().hashCode();
      }
      if (hasLoanDetailsProto()) {
        hash = (37 * hash) + LOANDETAILSPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getLoanDetailsProto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxnMessage.TxnResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage.TxnResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage.TxnResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage.TxnResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage.TxnResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnMessage.TxnResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnMessage.TxnResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxnMessage.TxnResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnMessage.TxnResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnMessage.TxnResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxnMessage.TxnResponseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TxnResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TxnResponseProto)
        TxnMessage.TxnResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TxnMessage.internal_static_VCBL_Transaction_TxnResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TxnMessage.internal_static_VCBL_Transaction_TxnResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxnMessage.TxnResponseProto.class, TxnMessage.TxnResponseProto.Builder.class);
      }

      // Construct using TxnMessage.TxnResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        microatmid_ = 0;

        timestamp_ = "";

        appVersion_ = "";

        status_ = 0;

        statusDescription_ = "";

        if (transactionProtoBuilder_ == null) {
          transactionProto_ = null;
        } else {
          transactionProto_ = null;
          transactionProtoBuilder_ = null;
        }
        if (loanDetailsProtoBuilder_ == null) {
          loanDetailsProto_ = null;
        } else {
          loanDetailsProto_ = null;
          loanDetailsProtoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TxnMessage.internal_static_VCBL_Transaction_TxnResponseProto_descriptor;
      }

      public TxnMessage.TxnResponseProto getDefaultInstanceForType() {
        return TxnMessage.TxnResponseProto.getDefaultInstance();
      }

      public TxnMessage.TxnResponseProto build() {
        TxnMessage.TxnResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxnMessage.TxnResponseProto buildPartial() {
        TxnMessage.TxnResponseProto result = new TxnMessage.TxnResponseProto(this);
        result.microatmid_ = microatmid_;
        result.timestamp_ = timestamp_;
        result.appVersion_ = appVersion_;
        result.status_ = status_;
        result.statusDescription_ = statusDescription_;
        if (transactionProtoBuilder_ == null) {
          result.transactionProto_ = transactionProto_;
        } else {
          result.transactionProto_ = transactionProtoBuilder_.build();
        }
        if (loanDetailsProtoBuilder_ == null) {
          result.loanDetailsProto_ = loanDetailsProto_;
        } else {
          result.loanDetailsProto_ = loanDetailsProtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxnMessage.TxnResponseProto) {
          return mergeFrom((TxnMessage.TxnResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxnMessage.TxnResponseProto other) {
        if (other == TxnMessage.TxnResponseProto.getDefaultInstance()) return this;
        if (other.getMicroatmid() != 0) {
          setMicroatmid(other.getMicroatmid());
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getAppVersion().isEmpty()) {
          appVersion_ = other.appVersion_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getStatusDescription().isEmpty()) {
          statusDescription_ = other.statusDescription_;
          onChanged();
        }
        if (other.hasTransactionProto()) {
          mergeTransactionProto(other.getTransactionProto());
        }
        if (other.hasLoanDetailsProto()) {
          mergeLoanDetailsProto(other.getLoanDetailsProto());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxnMessage.TxnResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxnMessage.TxnResponseProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int microatmid_ ;
      /**
       * <code>int32 microatmid = 1;</code>
       */
      public int getMicroatmid() {
        return microatmid_;
      }
      /**
       * <code>int32 microatmid = 1;</code>
       */
      public Builder setMicroatmid(int value) {
        
        microatmid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 microatmid = 1;</code>
       */
      public Builder clearMicroatmid() {
        
        microatmid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 2;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appVersion_ = "";
      /**
       * <code>string appVersion = 3;</code>
       */
      public java.lang.String getAppVersion() {
        java.lang.Object ref = appVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        java.lang.Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public Builder setAppVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public Builder clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 3;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.Status status = 4;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.Status status = 4;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Status status = 4;</code>
       */
      public Masters.Status getStatus() {
        Masters.Status result = Masters.Status.valueOf(status_);
        return result == null ? Masters.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.Status status = 4;</code>
       */
      public Builder setStatus(Masters.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Status status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object statusDescription_ = "";
      /**
       * <code>string statusDescription = 5;</code>
       */
      public java.lang.String getStatusDescription() {
        java.lang.Object ref = statusDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStatusDescriptionBytes() {
        java.lang.Object ref = statusDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public Builder setStatusDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public Builder clearStatusDescription() {
        
        statusDescription_ = getDefaultInstance().getStatusDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string statusDescription = 5;</code>
       */
      public Builder setStatusDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusDescription_ = value;
        onChanged();
        return this;
      }

      private Transaction.TransactionProto transactionProto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Transaction.TransactionProto, Transaction.TransactionProto.Builder, Transaction.TransactionProtoOrBuilder> transactionProtoBuilder_;
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public boolean hasTransactionProto() {
        return transactionProtoBuilder_ != null || transactionProto_ != null;
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Transaction.TransactionProto getTransactionProto() {
        if (transactionProtoBuilder_ == null) {
          return transactionProto_ == null ? Transaction.TransactionProto.getDefaultInstance() : transactionProto_;
        } else {
          return transactionProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Builder setTransactionProto(Transaction.TransactionProto value) {
        if (transactionProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactionProto_ = value;
          onChanged();
        } else {
          transactionProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Builder setTransactionProto(
          Transaction.TransactionProto.Builder builderForValue) {
        if (transactionProtoBuilder_ == null) {
          transactionProto_ = builderForValue.build();
          onChanged();
        } else {
          transactionProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Builder mergeTransactionProto(Transaction.TransactionProto value) {
        if (transactionProtoBuilder_ == null) {
          if (transactionProto_ != null) {
            transactionProto_ =
              Transaction.TransactionProto.newBuilder(transactionProto_).mergeFrom(value).buildPartial();
          } else {
            transactionProto_ = value;
          }
          onChanged();
        } else {
          transactionProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Builder clearTransactionProto() {
        if (transactionProtoBuilder_ == null) {
          transactionProto_ = null;
          onChanged();
        } else {
          transactionProto_ = null;
          transactionProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Transaction.TransactionProto.Builder getTransactionProtoBuilder() {
        
        onChanged();
        return getTransactionProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      public Transaction.TransactionProtoOrBuilder getTransactionProtoOrBuilder() {
        if (transactionProtoBuilder_ != null) {
          return transactionProtoBuilder_.getMessageOrBuilder();
        } else {
          return transactionProto_ == null ?
              Transaction.TransactionProto.getDefaultInstance() : transactionProto_;
        }
      }
      /**
       * <code>.TransactionProto transactionProto = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Transaction.TransactionProto, Transaction.TransactionProto.Builder, Transaction.TransactionProtoOrBuilder> 
          getTransactionProtoFieldBuilder() {
        if (transactionProtoBuilder_ == null) {
          transactionProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Transaction.TransactionProto, Transaction.TransactionProto.Builder, Transaction.TransactionProtoOrBuilder>(
                  getTransactionProto(),
                  getParentForChildren(),
                  isClean());
          transactionProto_ = null;
        }
        return transactionProtoBuilder_;
      }

      private Loandetails.LoanDetailsProto loanDetailsProto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Loandetails.LoanDetailsProto, Loandetails.LoanDetailsProto.Builder, Loandetails.LoanDetailsProtoOrBuilder> loanDetailsProtoBuilder_;
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public boolean hasLoanDetailsProto() {
        return loanDetailsProtoBuilder_ != null || loanDetailsProto_ != null;
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Loandetails.LoanDetailsProto getLoanDetailsProto() {
        if (loanDetailsProtoBuilder_ == null) {
          return loanDetailsProto_ == null ? Loandetails.LoanDetailsProto.getDefaultInstance() : loanDetailsProto_;
        } else {
          return loanDetailsProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Builder setLoanDetailsProto(Loandetails.LoanDetailsProto value) {
        if (loanDetailsProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loanDetailsProto_ = value;
          onChanged();
        } else {
          loanDetailsProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Builder setLoanDetailsProto(
          Loandetails.LoanDetailsProto.Builder builderForValue) {
        if (loanDetailsProtoBuilder_ == null) {
          loanDetailsProto_ = builderForValue.build();
          onChanged();
        } else {
          loanDetailsProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Builder mergeLoanDetailsProto(Loandetails.LoanDetailsProto value) {
        if (loanDetailsProtoBuilder_ == null) {
          if (loanDetailsProto_ != null) {
            loanDetailsProto_ =
              Loandetails.LoanDetailsProto.newBuilder(loanDetailsProto_).mergeFrom(value).buildPartial();
          } else {
            loanDetailsProto_ = value;
          }
          onChanged();
        } else {
          loanDetailsProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Builder clearLoanDetailsProto() {
        if (loanDetailsProtoBuilder_ == null) {
          loanDetailsProto_ = null;
          onChanged();
        } else {
          loanDetailsProto_ = null;
          loanDetailsProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Loandetails.LoanDetailsProto.Builder getLoanDetailsProtoBuilder() {
        
        onChanged();
        return getLoanDetailsProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      public Loandetails.LoanDetailsProtoOrBuilder getLoanDetailsProtoOrBuilder() {
        if (loanDetailsProtoBuilder_ != null) {
          return loanDetailsProtoBuilder_.getMessageOrBuilder();
        } else {
          return loanDetailsProto_ == null ?
              Loandetails.LoanDetailsProto.getDefaultInstance() : loanDetailsProto_;
        }
      }
      /**
       * <code>.LoanDetailsProto loanDetailsProto = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Loandetails.LoanDetailsProto, Loandetails.LoanDetailsProto.Builder, Loandetails.LoanDetailsProtoOrBuilder>
          getLoanDetailsProtoFieldBuilder() {
        if (loanDetailsProtoBuilder_ == null) {
          loanDetailsProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Loandetails.LoanDetailsProto, Loandetails.LoanDetailsProto.Builder, Loandetails.LoanDetailsProtoOrBuilder>(
                  getLoanDetailsProto(),
                  getParentForChildren(),
                  isClean());
          loanDetailsProto_ = null;
        }
        return loanDetailsProtoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TxnResponseProto)
    }

    // @@protoc_insertion_point(class_scope:TxnResponseProto)
    private static final TxnMessage.TxnResponseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxnMessage.TxnResponseProto();
    }

    public static TxnMessage.TxnResponseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxnResponseProto>
        PARSER = new com.google.protobuf.AbstractParser<TxnResponseProto>() {
      public TxnResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TxnResponseProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxnResponseProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxnResponseProto> getParserForType() {
      return PARSER;
    }

    public TxnMessage.TxnResponseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VCBL_Transaction_TxnRequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VCBL_Transaction_TxnRequestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VCBL_Transaction_TxnResponseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VCBL_Transaction_TxnResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TxnMessage.proto\022\020VCBL.Transaction\032\rMa" +
      "sters.proto\032\021Transaction.proto\032\021LoanDeta" +
      "ils.proto\"\212\001\n\017TxnRequestProto\022\022\n\nmicroat" +
      "mid\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\t\022\022\n\nappVersi" +
      "on\030\003 \001(\t\022<\n\020transactionProto\030\004 \001(\0132\".VCB" +
      "L.Transaction.TransactionProto\"\212\002\n\020TxnRe" +
      "sponseProto\022\022\n\nmicroatmid\030\001 \001(\005\022\021\n\ttimes" +
      "tamp\030\002 \001(\t\022\022\n\nappVersion\030\003 \001(\t\022$\n\006status" +
      "\030\004 \001(\0162\024.Status\022\031\n\021statusDe" +
      "scription\030\005 \001(\t\022<\n\020transactionProto\030\006 \001(",
      "\0132\".TransactionProto\022<\n" +
      "\020loanDetailsProto\030\007 \001(\0132\".VCBL.Transacti" +
      "on.LoanDetailsProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Masters.getDescriptor(),
          Transaction.getDescriptor(),
          Loandetails.getDescriptor(),
        }, assigner);
    internal_static_VCBL_Transaction_TxnRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VCBL_Transaction_TxnRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VCBL_Transaction_TxnRequestProto_descriptor,
        new java.lang.String[] { "Microatmid", "Timestamp", "AppVersion", "TransactionProto", });
    internal_static_VCBL_Transaction_TxnResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VCBL_Transaction_TxnResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VCBL_Transaction_TxnResponseProto_descriptor,
        new java.lang.String[] { "Microatmid", "Timestamp", "AppVersion", "Status", "StatusDescription", "TransactionProto", "LoanDetailsProto", });
    Masters.getDescriptor();
    Transaction.getDescriptor();
    Loandetails.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
